<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<AssemblyName>$(AssemblyName)</AssemblyName>
		<RootNamespace>$(AssemblyName)</RootNamespace>
		<PackageId>$(AssemblyName)</PackageId>
		<PackageOutputPath>../nupkgs</PackageOutputPath>
		<IsPackable>true</IsPackable>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<Description>Server-side abstractions for Hubcon.</Description>
		<RepositoryUrl>https://github.com/Brick-Logic/Hubcon</RepositoryUrl>
		<SignAssembly>true</SignAssembly>
		<AssemblyOriginatorKeyFile>$(MSBuildThisFileDirectory)HubconKey.snk</AssemblyOriginatorKeyFile>
		<PackageTags>rpc;dotnet;high-performance;native-aot;tcp;http;websockets</PackageTags>
		<Version>2.0.0-rc1</Version>
		<Authors>$(Authors)</Authors>
		<Company>$(Company)</Company>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<DebugType>embedded</DebugType>
		<Deterministic>True</Deterministic>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<DebugType>embedded</DebugType>
		<Deterministic>True</Deterministic>
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<!-- Development -->
	<ItemGroup Condition="'$(UsePackages)' != 'true'">	
		<ProjectReference Include="..\Hubcon.Shared.Abstractions.Standard\Hubcon.Shared.Abstractions.Standard.csproj" />
		<ProjectReference Include="..\Hubcon.Shared.Abstractions\Hubcon.Shared.Abstractions.csproj" />
		<ProjectReference Include="..\Hubcon.Shared.Core\Hubcon.Shared.Core.csproj" />
	</ItemGroup>

	<!-- Nuget -->
	<ItemGroup Condition="'$(UsePackages)' == 'true'">
		<PackageReference Include="Hubcon.Shared.Abstractions.Standard" Version="2.0.0-rc1" />
		<PackageReference Include="Hubcon.Shared.Abstractions" Version="2.0.0-rc1" />
		<PackageReference Include="Hubcon.Shared.Core" Version="2.0.0-rc1" />
	</ItemGroup>
	<ItemGroup>
	  <PackageReference Include="System.Text.Json" Version="[8.0.6, 11.0.0)" />
	</ItemGroup>
</Project>
