using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Hubcon.Analyzers.SourceGenerators
{
    [Generator]
    public class AuthManagerPreserverGenerator : IIncrementalGenerator
    {
        private const string TargetBaseType = "Hubcon.BaseAuthenticationManager";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var hasCallToInitializer = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: (node, _) => node is InvocationExpressionSyntax,
                    transform: (ctx, _) =>
                    {
                        var invocation = (InvocationExpressionSyntax)ctx.Node;

                        // Lookup by name
                        var name = "";

                        if (invocation.Expression is MemberAccessExpressionSyntax m)
                            name = m.Name.Identifier.Text;
                        else if (invocation.Expression is IdentifierNameSyntax i)
                            name = i.Identifier.Text;
                        else
                            name = null;


                        if (name != "AddHubconClient") return false;

                        // 1b. Validación Semántica
                        var symbol = ctx.SemanticModel.GetSymbolInfo(invocation).Symbol as IMethodSymbol;
                        if (symbol == null) return false;

                        return symbol.ContainingType?.Name == "DependencyInjection" &&
                               symbol.ContainingNamespace?.ToDisplayString() == "Hubcon";
                    })
                .Where(found => found)
                .Collect()
                .Select((calls, _) => calls.Any());

            IncrementalValuesProvider<ClassDeclarationSyntax> classDeclarations = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: (s, _) => s is ClassDeclarationSyntax && ((ClassDeclarationSyntax)s).BaseList != null,
                    transform: (ctx, _) => (ClassDeclarationSyntax)ctx.Node)
                .Where(m => m != null);

            var compilationAndClasses = context.CompilationProvider.Combine(classDeclarations.Collect());

            IncrementalValuesProvider<INamedTypeSymbol> authManagers = compilationAndClasses
                .SelectMany((pair, _) =>
                {
                    var results = new List<INamedTypeSymbol>();

                    var compilation = pair.Left;
                    var classes = pair.Right;

                    var targetSymbol = compilation.GetTypeByMetadataName(TargetBaseType);
                    if (targetSymbol == null) return results;

                    foreach (var classSyntax in classes)
                    {
                        var model = compilation.GetSemanticModel(classSyntax.SyntaxTree);
                        var classSymbol = model.GetDeclaredSymbol(classSyntax) as INamedTypeSymbol;

                        if (classSymbol != null && InheritsFrom(classSymbol, targetSymbol))
                        {
                            results.Add(classSymbol);
                        }
                    }

                    return results;
                });


            var finalProvider = authManagers.Combine(context.CompilationProvider.Select((c, _) => c.AssemblyName))
                .Combine(hasCallToInitializer);

            context.RegisterSourceOutput(finalProvider, (spc, data) =>
            {
                var ((symbol, assemblyName), shouldGenerate) = data;

                if (!shouldGenerate)
                    return;

                if (assemblyName == "Hubcon.Client")
                    return;

                string source = GeneratePreserverSource(symbol);
                spc.AddSource(symbol.Name + "_AuthPreserver.g.cs", SourceText.From(source, Encoding.UTF8));
            });
        }

        private static bool InheritsFrom(INamedTypeSymbol symbol, INamedTypeSymbol baseType)
        {
            var current = symbol.BaseType;
            while (current != null)
            {
                if (SymbolEqualityComparer.Default.Equals(current, baseType)) return true;
                current = current.BaseType;
            }

            return false;
        }

        private static string GeneratePreserverSource(INamedTypeSymbol symbol)
        {
            string fullTypeName = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            string className = symbol.Name;

            StringBuilder sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine("using System.Diagnostics.CodeAnalysis;");
            sb.AppendLine();
            sb.AppendLine("namespace Hubcon.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    internal static class " + className + "AuthPreserver");
            sb.AppendLine("    {");
            sb.AppendLine(
                "        #if UNITY_2017_1_OR_NEWER\r\n        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad)]\r\n        #else\r\n        [ModuleInitializer]\r\n        #endif");
            sb.AppendLine("        public static void Init()");
            sb.AppendLine("        {");
            sb.AppendLine($"            {Tools.GetCondition()}");
            sb.AppendLine("            {");

            // Preservar constructores
            int i = 0;
            foreach (var ctor in
                     symbol.InstanceConstructors.Where(c => c.DeclaredAccessibility == Accessibility.Public))
            {
                i++;
                var paramTypes = ctor.Parameters.Select(p =>
                    "(" + p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) + ")default");
                string paramsList = string.Join(", ", paramTypes);
                sb.AppendLine(
                    $"                var instance{i} = (global::Hubcon.Shared.Abstractions.Interfaces.IBuildableAuthenticationManager)(new " +
                    fullTypeName + "(" + paramsList + "));");

                // Preservar métodos
                foreach (var method in symbol.GetMembers().OfType<IMethodSymbol>().Where(m =>
                             m.MethodKind == MethodKind.Ordinary && m.DeclaredAccessibility == Accessibility.Public))
                {
                    var methodParamTypes = method.Parameters.Select(p =>
                        "(" + p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) + ")default");
                    string methodParamsList = string.Join(", ", methodParamTypes);
                    sb.AppendLine($"                instance{i}." + method.Name + "(" + methodParamsList + ");");
                }

                var targetInterface = symbol.AllInterfaces.FirstOrDefault(ts =>
                    ts.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) ==
                    "global::Hubcon.Shared.Abstractions.Interfaces.IBuildableAuthenticationManager");

                var classMethods = symbol.GetMembers().OfType<IMethodSymbol>();

                var interfaceMethods = targetInterface != null
                    ? targetInterface.GetMembers().OfType<IMethodSymbol>()
                    : Enumerable.Empty<IMethodSymbol>();

                var allMethods = classMethods.Concat(interfaceMethods)
                    .Where(m => m.MethodKind == MethodKind.Ordinary && m.DeclaredAccessibility == Accessibility.Public);

                foreach (var method in allMethods)
                {
                    var methodParamTypes = method.Parameters.Select(p =>
                        "(" + p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) + ")default!");
                    string methodParamsList = string.Join(", ", methodParamTypes);
                    sb.AppendLine($"                instance{i}." + method.Name + "(" + methodParamsList + ");");
                }
            }


            sb.AppendLine("            }");
            sb.AppendLine("            Preserve();");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(" + fullTypeName +
                          "))]");
            sb.AppendLine("        public static void Preserve() { }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }
    }
}