using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Hubcon.Analyzers.SourceGenerators.Extensions;
using Hubcon.Analyzers.SourceGenerators.GeneratorCommands;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Hubcon.Analyzers.SourceGenerators
{
    [Generator]
    public class DynamicPreserverGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var shouldExecuteForClient = context.GetHubconClientProvider();
            var shouldExecuteForServer = context.GetHubconServerProvider();

            // Tipos marcados locales (tienen el atributo físicamente en el código)
            var localMarkedTypes = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: (node, token) =>
                    {
                        var isClass = node is ClassDeclarationSyntax;
                        var isInterface = node is InterfaceDeclarationSyntax;
                        if (isClass || isInterface)
                        {
                            var typeDecl = (TypeDeclarationSyntax)node;
                            return typeDecl.AttributeLists.Count > 0;
                        }

                        return false;
                    },
                    transform: (ctx, token) => GetSymbolIfHasPreserveAttribute(ctx))
                .Where(c => c != null)
                .Collect();

            // Tipos externos/referenciados
            var referencedMarkedTypes = context.CompilationProvider.Select((compilation, token) =>
            {
                var results = new List<INamedTypeSymbol>();
                foreach (var reference in compilation.References)
                {
                    if (compilation.GetAssemblyOrModuleSymbol(reference) is IAssemblySymbol assembly)
                    {
                        if (assembly.Name == compilation.AssemblyName) continue;

                        if (assembly.Name == "Hubcon" || assembly.Name.StartsWith("Hubcon."))
                        {
                            CollectMarkedTypesInNamespace(assembly.GlobalNamespace, results);
                        }
                    }
                }

                return results.ToImmutableArray();
            });

            var shouldExecute = shouldExecuteForClient.Combine(shouldExecuteForServer);

            var finalProvider = localMarkedTypes
                .Combine(referencedMarkedTypes)
                .Combine(context.CompilationProvider)
                .Combine(shouldExecute);

            context.RegisterSourceOutput(finalProvider, (spc, data) =>
            {
                var (((localSymbols, referencedSymbols), compilation), shouldGenerate) = data;

                var generateForClient = shouldGenerate.Left;
                var generateForServer = shouldGenerate.Right;

                if (generateForClient == false && generateForServer == false) return;

                // Combinamos ambas listas de símbolos (locales + externos) en un único lote
                var allSeedSymbols = localSymbols.Concat(referencedSymbols).ToImmutableArray();
                if (allSeedSymbols.Length == 0) return;

                var classesToPreserve = ExpandPreservedSymbols(compilation, allSeedSymbols);

                if (classesToPreserve.Count == 0) return;

                var sbModules = new StringBuilder();
                var preserverCalls = new List<string>();
                
                var sbFinal = new StringBuilder();
                sbFinal.AppendLine("// <auto-generated />");
                sbFinal.AppendLine("using System;");
                sbFinal.AppendLine("using System.Runtime.CompilerServices;");
                sbFinal.AppendLine();
                sbFinal.AppendLine("namespace Hubcon.Generated.Preservers");
                sbFinal.AppendLine("{");

                foreach (var classSymbol in classesToPreserve)
                {
                    var safePreserverName = classSymbol.GetSafeName();

                    var result = GeneratePreserverForClass.Execute(classSymbol, safePreserverName, "    ");

                    sbModules.AppendLine(result.code);
                    sbModules.AppendLine();

                    preserverCalls.Add("Hubcon.Generated.Preservers." + result.preserverMethod);
                }

                sbFinal.AppendLine(sbModules.ToString());

                sbFinal.AppendLine(
                    "    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]");
                sbFinal.AppendLine("    public static class HubconMasterPreserverInitializer");
                sbFinal.AppendLine("    {");
                
                
                foreach (var classSymbol in classesToPreserve)
                {
                    sbFinal.AppendLine(
                        $"          [System.Diagnostics.CodeAnalysis.DynamicDependency(System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.All, typeof({classSymbol.ToDisplayString()}))]");
                    sbFinal.AppendLine(
                        $"          [System.Diagnostics.CodeAnalysis.DynamicDependency(System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors, typeof({classSymbol.ToDisplayString()}))]");
                }

                sbFinal.AppendLine("        #if UNITY_2017_1_OR_NEWER");
                sbFinal.AppendLine(
                    "        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad)]");
                sbFinal.AppendLine("        #else");
                sbFinal.AppendLine("        [ModuleInitializer]");
                sbFinal.AppendLine("        #endif");
                sbFinal.AppendLine("        public static void Init()");
                sbFinal.AppendLine("        {");
                sbFinal.AppendLine($"            {Tools.GetCondition()}");
                sbFinal.AppendLine("            {");

                for (int i = 0; i < preserverCalls.Count; i++)
                {
                    sbFinal.AppendLine("                " + preserverCalls[i]);
                }

                sbFinal.AppendLine("            }");
                sbFinal.AppendLine("        }");
                sbFinal.AppendLine("    }");
                sbFinal.AppendLine("}");

                spc.AddSource("HubconPreservers.g.cs", SourceText.From(sbFinal.ToString(), Encoding.UTF8));
            });
        }

        private static INamedTypeSymbol GetSymbolIfHasPreserveAttribute(GeneratorSyntaxContext ctx)
        {
            var symbol = ctx.SemanticModel.GetDeclaredSymbol(ctx.Node) as INamedTypeSymbol;
            if (symbol == null) return null;

            var attributes = symbol.GetAttributes();
            for (int i = 0; i < attributes.Length; i++)
            {
                var attrClass = attributes[i].AttributeClass;
                if (attrClass != null &&
                    attrClass.Name == "HubconPreserveAttribute" &&
                    attrClass.ContainingNamespace?.ToDisplayString() == "Hubcon")
                {
                    return symbol;
                }
            }

            return null;
        }

        private static bool HasPreserveAttribute(INamedTypeSymbol symbol)
        {
            if (symbol == null) return false;

            var attributes = symbol.GetAttributes();
            for (int i = 0; i < attributes.Length; i++)
            {
                var attrClass = attributes[i].AttributeClass;
                if (attrClass != null &&
                    attrClass.Name == "HubconPreserveAttribute" &&
                    attrClass.ContainingNamespace?.ToDisplayString() == "Hubcon")
                {
                    return true;
                }
            }

            return false;
        }

        private static HashSet<INamedTypeSymbol> ExpandPreservedSymbols(Compilation compilation,
            System.Collections.Immutable.ImmutableArray<INamedTypeSymbol> markedSymbols)
        {
            var result = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);

            var targetInterfaces = markedSymbols.Where(s => s.TypeKind == TypeKind.Interface)
                .ToImmutableHashSet(SymbolEqualityComparer.Default);
            var targetClasses = markedSymbols.Where(s => s.TypeKind == TypeKind.Class)
                .ToImmutableHashSet(SymbolEqualityComparer.Default);

            foreach (var targetClass in targetClasses)
            {
                if (targetClass is INamedTypeSymbol symbol)
                    result.Add(symbol);
            }

            // Acción unificada para evaluar si una clase debe ser preservada
            Action<INamedTypeSymbol> evaluateClass = currentClass =>
            {
                if (targetInterfaces.Count > 0)
                {
                    var interfaces = currentClass.AllInterfaces;
                    for (int i = 0; i < interfaces.Length; i++)
                    {
                        if (targetInterfaces.Contains(interfaces[i]))
                        {
                            result.Add(currentClass);
                            return;
                        }
                    }
                }

                if (targetClasses.Count > 0)
                {
                    var baseType = currentClass.BaseType;
                    while (baseType != null)
                    {
                        if (targetClasses.Contains(baseType))
                        {
                            result.Add(currentClass);
                            return;
                        }

                        baseType = baseType.BaseType;
                    }
                }
            };

            GetAllAssemblyClasses(compilation.GlobalNamespace, evaluateClass);

            foreach (var reference in compilation.References)
            {
                var assemblySymbol = compilation.GetAssemblyOrModuleSymbol(reference) as IAssemblySymbol;
                if (assemblySymbol != null)
                {
                    var name = assemblySymbol.Name;
                    if (name == "Hubcon" || name.StartsWith("Hubcon."))
                    {
                        GetAllAssemblyClasses(assemblySymbol.GlobalNamespace, evaluateClass);
                    }
                }
            }

            return result;
        }

        private static void GetAllAssemblyClasses(INamespaceSymbol namespaceSymbol,
            Action<INamedTypeSymbol> onClassFound)
        {
            foreach (var member in namespaceSymbol.GetMembers())
            {
                if (member is INamespaceSymbol nestedNamespace)
                {
                    GetAllAssemblyClasses(nestedNamespace, onClassFound);
                }
                else if (member is INamedTypeSymbol typeSymbol)
                {
                    if (typeSymbol.TypeKind == TypeKind.Class)
                    {
                        onClassFound(typeSymbol);
                    }

                    if (typeSymbol.GetTypeMembers().Length > 0)
                    {
                        ProcessNestedTypes(typeSymbol, onClassFound);
                    }
                }
            }
        }

        private static void CollectMarkedTypesInNamespace(INamespaceSymbol ns, List<INamedTypeSymbol> results)
        {
            foreach (var member in ns.GetMembers())
            {
                if (member is INamespaceSymbol nestedNs)
                {
                    CollectMarkedTypesInNamespace(nestedNs, results);
                }
                else if (member is INamedTypeSymbol type)
                {
                    if (member.ContainingNamespace.Name != "Hubcon")
                        return;

                    if (HasPreserveAttribute(type))
                    {
                        results.Add(type);
                    }

                    if (type.GetTypeMembers().Length > 0)
                    {
                        CollectMarkedTypesInNested(type, results);
                    }
                }
            }
        }

        private static void CollectMarkedTypesInNested(INamedTypeSymbol type, List<INamedTypeSymbol> results)
        {
            var nestedTypes = type.GetTypeMembers();
            for (int i = 0; i < nestedTypes.Length; i++)
            {
                var nestedType = nestedTypes[i];

                if (HasPreserveAttribute(nestedType))
                {
                    results.Add(nestedType);
                }

                if (nestedType.GetTypeMembers().Length > 0)
                {
                    CollectMarkedTypesInNested(nestedType, results);
                }
            }
        }

        private static void ProcessNestedTypes(INamedTypeSymbol typeSymbol, Action<INamedTypeSymbol> onClassFound)
        {
            foreach (var nestedType in typeSymbol.GetTypeMembers())
            {
                if (nestedType.TypeKind == TypeKind.Class)
                {
                    onClassFound(nestedType);
                }

                if (nestedType.GetTypeMembers().Length > 0)
                {
                    ProcessNestedTypes(nestedType, onClassFound);
                }
            }
        }
    }
}