using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Hubcon.Analyzers.SourceGenerators.Extensions;
using Hubcon.Analyzers.SourceGenerators.GeneratorCommands;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Hubcon.Analyzers.SourceGenerators
{
    // [Generator]
    // public class DynamicPreserverGenerator : IIncrementalGenerator
    // {
    //     public void Initialize(IncrementalGeneratorInitializationContext context)
    //     {
    //         var shouldExecuteForClient = context.GetHubconClientProvider();
    //         var shouldExecuteForServer = context.GetHubconServerProvider();
    //
    //         // Tipos marcados locales (tienen el atributo físicamente en el código)
    //         var localMarkedTypes = context.SyntaxProvider
    //             .CreateSyntaxProvider(
    //                 predicate: (node, token) =>
    //                 {
    //                     var isClass = node is ClassDeclarationSyntax;
    //                     var isInterface = node is InterfaceDeclarationSyntax;
    //                     if (isClass || isInterface)
    //                     {
    //                         var typeDecl = (TypeDeclarationSyntax)node;
    //                         return typeDecl.AttributeLists.Count > 0;
    //                     }
    //
    //                     return false;
    //                 },
    //                 transform: (ctx, token) => GetSymbolIfHasPreserveAttribute(ctx))
    //             .Where(c => c != null)
    //             .Collect();
    //
    //         // Tipos externos/referenciados
    //         var referencedMarkedTypes = context.CompilationProvider.Select((compilation, token) =>
    //         {
    //             var results = new List<INamedTypeSymbol>();
    //             foreach (var reference in compilation.References)
    //             {
    //                 if (compilation.GetAssemblyOrModuleSymbol(reference) is IAssemblySymbol assembly)
    //                 {
    //                     if (assembly.Name == compilation.AssemblyName) continue;
    //
    //                     if (assembly.Name == "Hubcon" || assembly.Name.StartsWith("Hubcon."))
    //                     {
    //                         CollectMarkedTypesInNamespace(assembly.GlobalNamespace, results);
    //                     }
    //                 }
    //             }
    //
    //             return results.ToImmutableArray();
    //         });
    //         
    //         var controllerClasses = context.SyntaxProvider
    //             .CreateSyntaxProvider(
    //                 predicate: (node, _) => SymbolTools.IsCandidateClass(node),
    //                 transform: (ctx, _) => SymbolTools.GetClassSymbolIfImplementsInterface(ctx))
    //             .Where(c => c != null)
    //             .Collect();
    //
    //         var shouldExecute = shouldExecuteForClient.Combine(shouldExecuteForServer);
    //
    //         var finalProvider = localMarkedTypes
    //             .Combine(referencedMarkedTypes)
    //             .Combine(controllerClasses)
    //             .Combine(context.CompilationProvider)
    //             .Combine(shouldExecute);
    //
    //         context.RegisterSourceOutput(finalProvider, (spc, data) =>
    //         {
    //             var ((((localSymbols, referencedSymbols), controllers), compilation), shouldGenerate) = data;
    //
    //             var generateForClient = shouldGenerate.Left;
    //             var generateForServer = shouldGenerate.Right;
    //
    //             if (generateForClient == false && generateForServer == false) return;
    //
    //             NewMethod(localSymbols, referencedSymbols, compilation, controllers, spc);
    //         });
    //     }
    //
    //     private static void NewMethod(ImmutableArray<INamedTypeSymbol> localSymbols, ImmutableArray<INamedTypeSymbol> referencedSymbols, Compilation compilation,
    //         ImmutableArray<INamedTypeSymbol> controllers, SourceProductionContext spc)
    //     {
    //         // Combinamos ambas listas de símbolos (locales + externos) en un único lote
    //         var allSeedSymbols = localSymbols.Concat(referencedSymbols).ToImmutableArray();
    //         if (allSeedSymbols.Length == 0) return;
    //
    //         var classesToPreserve = ExpandPreservedSymbols(compilation, allSeedSymbols);
    //
    //         if (classesToPreserve.Count == 0) return;
    //
    //         var sbModules = new StringBuilder();
    //         var preserverCalls = new List<string>();
    //             
    //         var sbFinal = new StringBuilder();
    //         sbFinal.AppendLine("// <auto-generated />");
    //         sbFinal.AppendLine("using System;");
    //         sbFinal.AppendLine("using System.Runtime.CompilerServices;");
    //         sbFinal.AppendLine();
    //         sbFinal.AppendLine("namespace Hubcon.Generated.Preservers");
    //         sbFinal.AppendLine("{");
    //
    //         foreach (var classSymbol in classesToPreserve)
    //         {
    //             var safePreserverName = classSymbol.GetSafeName();
    //
    //             var result = GeneratePreserverForClass.Execute(classSymbol, safePreserverName, "    ");
    //
    //             sbModules.AppendLine(result.code);
    //             sbModules.AppendLine();
    //
    //             preserverCalls.Add("Hubcon.Generated.Preservers." + result.preserverMethod);
    //         }
    //
    //         sbFinal.AppendLine(sbModules.ToString());
    //
    //         sbFinal.AppendLine(
    //             "    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]");
    //         sbFinal.AppendLine("    public class HubconMasterPreserverInitializer");
    //         sbFinal.AppendLine("    {");
    //             
    //             
    //         foreach (var classSymbol in classesToPreserve)
    //         {
    //             sbFinal.AppendLine(
    //                 $"          [System.Diagnostics.CodeAnalysis.DynamicDependency(System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.All, typeof({classSymbol.ToDisplayString()}))]");
    //             sbFinal.AppendLine(
    //                 $"          [System.Diagnostics.CodeAnalysis.DynamicDependency(System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors, typeof({classSymbol.ToDisplayString()}))]");
    //         }
    //
    //         sbFinal.AppendLine("        #if UNITY_2017_1_OR_NEWER");
    //         sbFinal.AppendLine(
    //             "        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad)]");
    //         sbFinal.AppendLine("        #else");
    //         sbFinal.AppendLine("        [ModuleInitializer]");
    //         sbFinal.AppendLine("        #endif");
    //         sbFinal.AppendLine("        public static void Init()");
    //         sbFinal.AppendLine("        {");
    //         sbFinal.AppendLine($"            {Tools.GetCondition()}");
    //         sbFinal.AppendLine("            {");
    //
    //         for (int i = 0; i < preserverCalls.Count; i++)
    //         {
    //             sbFinal.AppendLine("                " + preserverCalls[i]);
    //         }
    //
    //         sbFinal.AppendLine("            }");
    //         sbFinal.AppendLine("        }");
    //         sbFinal.AppendLine("    }");
    //         sbFinal.AppendLine("}");
    //
    //         var classesToGenerateFactory = new List<INamedTypeSymbol>();
    //         classesToGenerateFactory.AddRange(controllers);
    //         classesToGenerateFactory.AddRange(classesToPreserve);
    //             
    //         spc.AddSource("HubconPreservers.g.cs", SourceText.From(sbFinal.ToString(), Encoding.UTF8));
    //         GenerateFactories.Execute(spc, classesToGenerateFactory, "ServiceFactory", "ServiceFactoriesModule.g.cs");
    //     }
    // }
}