using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Hubcon.Analyzers.SourceGenerators
{
    [Generator]
    public class TransportClientGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var hasCallToInitializer = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: (node, _) => node is InvocationExpressionSyntax,
                    transform: (ctx, _) =>
                    {
                        var invocation = (InvocationExpressionSyntax)ctx.Node;

                        // 1. Filtro por nombre
                        var name = "";

                        if (invocation.Expression is MemberAccessExpressionSyntax m)
                            name = m.Name.Identifier.Text;
                        else if (invocation.Expression is IdentifierNameSyntax i)
                            name = i.Identifier.Text;
                        else
                            name = null;


                        if (name != "AddHubconClient") return false;

                        var symbol = ctx.SemanticModel.GetSymbolInfo(invocation).Symbol as IMethodSymbol;
                        if (symbol == null) return false;

                        return symbol.ContainingType?.Name == "DependencyInjection" &&
                               symbol.ContainingNamespace?.ToDisplayString() == "Hubcon";
                    })
                .Where(found => found)
                .Collect()
                .Select((calls, _) => calls.Any());

            var provider = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: (s, _) => s is ClassDeclarationSyntax cds && cds.BaseList != null,
                    transform: GetTransportMapping)
                .Where(m => m != null)
                .Collect();

            var finalProvider = provider
                .Combine(context.CompilationProvider.Select((c, _) => c.AssemblyName))
                .Combine(hasCallToInitializer);

            context.RegisterSourceOutput(finalProvider, (spc, data) =>
            {
                var ((source, assemblyName), shouldGenerate) = data;

                if (!shouldGenerate)
                    return;

                if (assemblyName == "Hubcon.Client")
                    return;

                Execute(spc, source);
            });
        }

        private static (string MarkerType, string ClientType)? GetTransportMapping(GeneratorSyntaxContext context, CancellationToken ct)
        {
            var classSymbol = context.SemanticModel.GetDeclaredSymbol((ClassDeclarationSyntax)context.Node) as INamedTypeSymbol;
            if (classSymbol == null) return null;

            foreach (var i in classSymbol.AllInterfaces)
            {
                // Validamos Nombre, Cantidad de Argumentos y Namespace
                if (i.TypeArguments.Length == 1 && i.ContainingNamespace.ToDisplayString() == "Hubcon.TransportClient")
                {
                    return (
                        i.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                        classSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                    );
                }
            }
            return null;
        }

        private void Execute(SourceProductionContext context, ImmutableArray<(string MarkerType, string ClientType)?> mappings)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine("using Hubcon.Client.Core.Transports;");
            sb.AppendLine();
            sb.AppendLine("namespace Hubcon.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    internal static class TransportLookup");
            sb.AppendLine("    {");
            sb.AppendLine("        #if UNITY_2017_1_OR_NEWER\r\n        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad)]\r\n        #else\r\n        [ModuleInitializer]\r\n        #endif");
            sb.AppendLine("        internal static void Initialize()");
            sb.AppendLine("        {");
            sb.AppendLine("            var mappings = new Dictionary<Type, Type>();");

            foreach (var map in mappings.Distinct())
            {
                if (map.HasValue)
                {
                    sb.AppendLine($"            mappings[typeof({map.Value.MarkerType})] = typeof({map.Value.ClientType});");
                }
            }

            // Registramos este lote de transportes en la factoría central
            sb.AppendLine("            global::Hubcon.Client.Core.Transports.TransportTypeResolver.RegisterMappings(mappings);");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            context.AddSource("TransportLookup.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }
    }
}