using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Hubcon.Generators
{
    [Generator]
    public class TransportClientPreserverGenerator : IIncrementalGenerator
    {
        private const string TargetBaseType = "Hubcon.TransportClient";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var localTypes = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: (s, _) => s is ClassDeclarationSyntax cds && cds.BaseList != null,
                    transform: (ctx, _) => GetIfDerived(ctx.SemanticModel.GetDeclaredSymbol(ctx.Node) as INamedTypeSymbol))
                .Where(t => t != null);

            var referencedTypes = context.CompilationProvider.Select((compilation, _) =>
            {
                var results = new List<INamedTypeSymbol>();
                foreach (var reference in compilation.References)
                {
                    if (compilation.GetAssemblyOrModuleSymbol(reference) is IAssemblySymbol assembly)
                    {
                        if (assembly.Name == compilation.AssemblyName) continue;
                        CollectImplementations(assembly.GlobalNamespace, results);
                    }
                }
                return results.ToImmutableArray();
            });

            var allTypes = localTypes.Collect().Combine(referencedTypes);
            context.RegisterSourceOutput(allTypes, (spc, source) => Execute(source.Left, source.Right, spc));
        }

        private static INamedTypeSymbol GetIfDerived(INamedTypeSymbol symbol)
        {
            if (symbol == null) return null;
            var current = symbol.BaseType;
            while (current != null)
            {
                if (current.ToDisplayString().StartsWith(TargetBaseType)) return symbol;
                current = current.BaseType;
            }
            return null;
        }

        private static void CollectImplementations(INamespaceSymbol ns, List<INamedTypeSymbol> results)
        {
            foreach (var type in ns.GetTypeMembers())
            {
                var match = GetIfDerived(type);
                if (match != null && match.DeclaredAccessibility == Accessibility.Public) results.Add(match);
            }
            foreach (var nestedNs in ns.GetNamespaceMembers()) CollectImplementations(nestedNs, results);
        }

        private static void Execute(ImmutableArray<INamedTypeSymbol> local, ImmutableArray<INamedTypeSymbol> referenced, SourceProductionContext context)
        {
            var combined = local.AddRange(referenced).Distinct(SymbolEqualityComparer.Default);
            if (combined.Count() == 0) return;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine("using System.Diagnostics.CodeAnalysis;");
            sb.AppendLine();
            sb.AppendLine("namespace Hubcon.Generated");
            sb.AppendLine("{");

            // --- POLYFILLS ---
            sb.AppendLine("    #if !NET5_0_OR_GREATER");
            sb.AppendLine("    namespace System.Runtime.CompilerServices { [AttributeUsage(AttributeTargets.Method)] internal sealed class ModuleInitializerAttribute : Attribute { } }");
            sb.AppendLine("    #endif");
            sb.AppendLine("    #if !NETCOREAPP3_0_OR_GREATER");
            sb.AppendLine("    namespace System.Diagnostics.CodeAnalysis { [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)] internal sealed class DynamicDependencyAttribute : Attribute { public DynamicDependencyAttribute(DynamicallyAccessedMemberTypes memberTypes, Type type) { } } }");
            sb.AppendLine("    #endif");
            sb.AppendLine();

            sb.AppendLine("    internal static class TransportClientPreserver");
            sb.AppendLine("    {");

            // --- ATRIBUTOS DYNAMIC DEPENDENCY ---
            foreach (INamedTypeSymbol type in combined)
            {
                string typeName = GetSafeTypeName(type);
                sb.AppendLine("        [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(" + typeName + "))]");
            }

            sb.AppendLine("        [ModuleInitializer]");
            sb.AppendLine("        public static void Init()");
            sb.AppendLine("        {");
            sb.AppendLine("            if (Environment.TickCount < 0)");
            sb.AppendLine("            {");

            foreach (INamedTypeSymbol type in combined)
            {
                string typeName = GetSafeTypeName(type);

                // Constructores
                int i = 0;
                foreach (var ctor in type.InstanceConstructors.Where(c => c.DeclaredAccessibility == Accessibility.Public))
                {
                    i++;
                    sb.AppendLine($"                {typeName} {type.Name}Variable{i} = new " + typeName + "(" + GetDefaultArgs(ctor) + ");");

                    // Métodos
                    foreach (var method in type.GetMembers().OfType<IMethodSymbol>().Where(m => m.MethodKind == MethodKind.Ordinary && m.DeclaredAccessibility == Accessibility.Public))
                    {
                        string methodName = method.IsGenericMethod ? method.Name + "<" + string.Join(", ", method.TypeParameters.Select(tp => "object")) + ">" : method.Name;
                        sb.AppendLine($"                {type.Name}Variable{i}." + methodName + "(" + GetDefaultArgs(method) + ");");
                    }
                }
            }

            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            context.AddSource("TransportClientPreserver.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private static string GetSafeTypeName(INamedTypeSymbol type)
        {
            string name = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            if (type.IsGenericType)
            {
                name += "<" + string.Join(", ", type.TypeParameters.Select(tp => "object")) + ">";
            }
            return name;
        }

        private static string GetDefaultArgs(IMethodSymbol method)
        {
            return string.Join(", ", method.Parameters.Select(p => "default(" + p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) + ")"));
        }
    }
}