using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;

namespace Hubcon.Analyzers.SourceGenerators
{
    [Generator]
    public class TrimAttributesGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var hasCallToInitializer = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: (node, _) => node is InvocationExpressionSyntax,
                    transform: (ctx, _) =>
                    {
                        var invocation = (InvocationExpressionSyntax)ctx.Node;

                        // 1a. Filtro rápido por nombre (No gasta CPU)
                        var name = "";

                        if (invocation.Expression is MemberAccessExpressionSyntax m)
                            name = m.Name.Identifier.Text;
                        else if (invocation.Expression is IdentifierNameSyntax i)
                            name = i.Identifier.Text;
                        else
                            name = null;


                        if (name != "AddHubconClient") return false;

                        // 1b. Validación Semántica (La verdad absoluta)
                        var symbol = ctx.SemanticModel.GetSymbolInfo(invocation).Symbol as IMethodSymbol;
                        if (symbol == null) return false;

                        // Verificamos: Namespace == "Hubcon" && Clase == "DependencyInjection"
                        return symbol.ContainingType?.Name == "DependencyInjection" &&
                               symbol.ContainingNamespace?.ToDisplayString() == "Hubcon";
                    })
                .Where(found => found)
                .Collect()
                .Select((calls, _) => calls.Any());

            var provider = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: (s, _) => s is ClassDeclarationSyntax cds && cds.BaseList != null,
                    transform: (ctx, _) => (ClassDeclarationSyntax)ctx.Node)
                .Where(m => m != null)
                .Collect();

            var finalProvider = provider
                .Combine(context.CompilationProvider.Select((c, _) => c.AssemblyName))
                .Combine(hasCallToInitializer);

            context.RegisterSourceOutput(finalProvider, (spc, data) =>
            {
                var ((source, assemblyName), shouldGenerate) = data;

                if (!shouldGenerate)
                    return;

                if (assemblyName == "Hubcon.Client")
                    return;

                Execute(spc);
            });
        }

        private void Execute(SourceProductionContext context)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine(@"
namespace System.Diagnostics.CodeAnalysis
{
    [AttributeUsage(AttributeTargets.GenericParameter | AttributeTargets.Parameter | AttributeTargets.Field | AttributeTargets.Property | AttributeTargets.Method | AttributeTargets.Class | AttributeTargets.Interface, AllowMultiple = false, Inherited = false)]
    internal sealed class DynamicallyAccessedMembersAttribute : Attribute
    {
        public DynamicallyAccessedMembersAttribute(DynamicallyAccessedMemberTypes memberTypes)
        {
            MemberTypes = memberTypes;
        }

        public DynamicallyAccessedMemberTypes MemberTypes { get; }
    }

    [Flags]
    internal enum DynamicallyAccessedMemberTypes
    {
        None = 0,
        PublicParameterlessConstructor = 0x0001,
        PublicConstructors = 0x0002,
        NonPublicConstructors = 0x0004,
        PublicMethods = 0x0008,
        NonPublicMethods = 0x0010,
        PublicFields = 0x0020,
        NonPublicFields = 0x0040,
        PublicProperties = 0x0080,
        NonPublicProperties = 0x0100,
        PublicEvents = 0x0200,
        NonPublicEvents = 0x0400,
        All = -1
    }
}

namespace System.Diagnostics.CodeAnalysis 
{ 
    [AttributeUsage(
        AttributeTargets.Constructor | AttributeTargets.Method | AttributeTargets.Field, 
        AllowMultiple = true, 
        Inherited = false)]
    internal sealed class DynamicDependencyAttribute : Attribute
    {
        public string MemberSignature { get; }
        public Type TargetType { get; }
        public string AssemblyName { get; }
        public DynamicallyAccessedMemberTypes MemberTypes { get; }

        // Sobrecarga por Firma de Miembro y Tipo
        public DynamicDependencyAttribute(string memberSignature, Type type)
        {
            MemberSignature = memberSignature;
            TargetType = type;
        }

        // Sobrecarga por Firma de Miembro, Nombre de Tipo y Nombre de Assembly
        public DynamicDependencyAttribute(string memberSignature, string typeName, string assemblyName)
        {
            MemberSignature = memberSignature;
            // Aquí podrías agregar lógica para resolver el tipo si fuera necesario
            AssemblyName = assemblyName;
        }

        // Sobrecarga por Flags de Miembros y Tipo (La que más vas a usar en DI)
        public DynamicDependencyAttribute(DynamicallyAccessedMemberTypes memberTypes, Type type)
        {
            MemberTypes = memberTypes;
            TargetType = type;
        }

        // Sobrecarga por Flags de Miembros, Nombre de Tipo y Nombre de Assembly
        public DynamicDependencyAttribute(DynamicallyAccessedMemberTypes memberTypes, string typeName, string assemblyName)
        {
            MemberTypes = memberTypes;
            AssemblyName = assemblyName;
        }
    }
}");   

            context.AddSource("TrimAttributes.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }
    }
}