using System.Collections.Generic;
using System.Linq;
using System.Text;
using Hubcon.Analyzers.SourceGenerators.Extensions;
using HubconAnalyzers.SourceGenerators.Extensions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Hubcon.Analyzers.SourceGenerators.GeneratorCommands
{
    public static class GenerateControllerPreservers
    {
        public static void Execute(SourceProductionContext spc, IEnumerable<INamedTypeSymbol> controllers, string fileName)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Threading;");
            sb.AppendLine("using Hubcon;");
            sb.AppendLine("using Hubcon.Generated;");
            sb.AppendLine("using System.Runtime.CompilerServices;");

            foreach (var controller in controllers)
            {
                sb.AppendLine();
                sb.AppendLine($"namespace {controller.ContainingNamespace}");
                sb.AppendLine("{");
                var preserver = GeneratePreserverClass.Execute(controller, "");
                sb.AppendLine(preserver);
                sb.AppendLine("}");
            }
            
            sb.AppendLine();

            var code = sb.ToString();
            spc.AddSource(fileName, SourceText.From(code, Encoding.UTF8));
        }
    }
}