using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Hubcon.Analyzers.SourceGenerators.Extensions;
using HubconAnalyzers.SourceGenerators.Extensions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Hubcon.Analyzers.SourceGenerators.GeneratorCommands
{
    public static class GenerateEndpointParameterWrappers
    {
        public static void Execute(SourceProductionContext spc, IEnumerable<INamedTypeSymbol> interfaces, string fileName)
        {
             var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.ComponentModel;");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine("using System.Runtime.Serialization;");
            sb.AppendLine("using System.Threading;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine("using Microsoft.AspNetCore.Http;");
            sb.AppendLine("using Microsoft.AspNetCore.Mvc.ModelBinding;");
            sb.AppendLine();
            sb.AppendLine("namespace Hubcon.Generated");
            sb.AppendLine("{");

            sb.AppendLine($"    public static class ParameterWrapperProvider");
            sb.AppendLine("    {");
            sb.AppendLine(
                "        #if UNITY_2017_1_OR_NEWER\r\n        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad)]\r\n        #else\r\n        [ModuleInitializer]\r\n        #endif");
            sb.AppendLine("        public static void Init()");
            sb.AppendLine("        {");
            sb.AppendLine(
                "             global::Hubcon.EndpointManager.Setup(EndpointDelegateProvider.GetDelegate, EndpointInvokerProvider.GetInvoker, ParameterWrapperProvider.GetWrapperType, ParameterWrapperProvider.GetWrapperDelegate);");
            sb.AppendLine("        }");
            sb.AppendLine();

            sb.AppendLine("        public static Type? GetWrapperType(string contractName, string signature)");
            sb.AppendLine("        {");
            sb.AppendLine("            var finalSignature = contractName + \"_\" + signature;");
            sb.AppendLine("            switch(finalSignature)");
            sb.AppendLine("            {");
            foreach (var interfaceSymbol in interfaces)
            {
                var methods = interfaceSymbol.GetMembers()
                    .OfType<IMethodSymbol>()
                    .Where(m => m.MethodKind == MethodKind.Ordinary);


                foreach (var method in methods)
                {
                    if (method.Parameters.Count(x => x.ToDisplayString() != "System.Threading.CancellationToken") == 0)
                        continue;

                    var wrapperClassName =
                        $"{interfaceSymbol.GetSafeName()}_{method.GetMethodSymbolSignature()}_Request";

                    sb.AppendLine(
                        $"                 case \"{interfaceSymbol.Name}_{method.GetMethodSymbolSignature()}\": return typeof({wrapperClassName});");
                }
            }

            sb.AppendLine("                 default: return null;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");

            sb.AppendLine();

            sb.AppendLine(
                "        public static Func<IReadOnlyDictionary<string, object>, object>? GetWrapperDelegate(string contractName, string signature)");
            sb.AppendLine("        {");
            sb.AppendLine("            var finalSignature = contractName + \"_\" + signature;");
            sb.AppendLine("            switch(finalSignature)");
            sb.AppendLine("            {");

            foreach (var interfaceSymbol in interfaces)
            {
                var methods = interfaceSymbol.GetMembers()
                    .OfType<IMethodSymbol>()
                    .Where(m => m.MethodKind == MethodKind.Ordinary);


                foreach (var method in methods)
                {
                    if (method.Parameters.Count(x => x.ToDisplayString() != "System.Threading.CancellationToken") == 0)
                        continue;

                    var wrapperClassName =
                        $"{interfaceSymbol.GetSafeName()}_{method.GetMethodSymbolSignature()}_Request";

                    sb.AppendLine(
                        $"                 case \"{interfaceSymbol.Name}_{method.GetMethodSymbolSignature()}\":return {wrapperClassName}.GetWrapped;");
                }
            }

            sb.AppendLine("                 default: return null;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();

            foreach (var interfaceSymbol in interfaces)
            {
                var methods = interfaceSymbol.GetMembers()
                    .OfType<IMethodSymbol>()
                    .Where(m => m.MethodKind == MethodKind.Ordinary);

                foreach (var method in methods)
                {
                    if (method.Parameters.Count(x => x.ToDisplayString() != "System.Threading.CancellationToken") == 0)
                        continue;

                    var wrapperClassName =
                        $"{interfaceSymbol.GetSafeName()}_{method.GetMethodSymbolSignature()}_Request";

                    sb.AppendLine($"    public sealed class {wrapperClassName} : global::Hubcon.IWrapper");
                    sb.AppendLine("    {");

                    var parameters = method.Parameters
                        .Where(x => x.ToDisplayString() != "System.Threading.CancellationToken")
                        .ToImmutableArray();

                    foreach (var param in parameters)
                    {
                        string typeName = param.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                        string paramName = param.Name;

                        foreach (var attr in param.GetAttributes())
                        {
                            var attrNamespace = attr.AttributeClass?.ContainingNamespace?.ToDisplayString();

                            if (attrNamespace == "System.Runtime.CompilerServices")
                            {
                                continue;
                            }

                            sb.AppendLine($"        [{attr.AttributeClass.ToDisplayString()}]");
                        }

                        var isNullable = false;
                        // Clonamos el valor por defecto si existe
                        if (param.HasExplicitDefaultValue)
                        {
                            object defaultVal = param.ExplicitDefaultValue;
                            string valStr;

                            if (defaultVal == null)
                            {
                                isNullable = true;
                            }
                            else
                            {
                                switch (defaultVal)
                                {
                                    case string s:
                                        valStr = "\"" + s + "\"";
                                        break;
                                    case bool b:
                                        valStr = b ? "true" : "false";
                                        break;
                                    case double d:
                                        valStr = d.ToString(System.Globalization.CultureInfo.InvariantCulture) + "d";
                                        break;
                                    case float f:
                                        valStr = f.ToString(System.Globalization.CultureInfo.InvariantCulture) + "f";
                                        break;
                                    case decimal dec:
                                        valStr = dec.ToString(System.Globalization.CultureInfo.InvariantCulture) + "m";
                                        break;
                                    default:
                                        valStr = defaultVal.ToString();
                                        break;
                                }

                                sb.AppendLine($"        [DefaultValue({valStr})]");
                            }
                        }

                        sb.AppendLine(
                            $"        public {typeName}{(isNullable ? "?" : "")} {paramName} {{ get; set; }}");
                        sb.AppendLine();
                    }

                    if (parameters.Length > 0)
                    {
                        sb.AppendLine(
                            $"        public static object GetWrapped(IReadOnlyDictionary<string, object> parameters_{method.GetMethodSymbolSignature()})");
                        sb.AppendLine("        {");
                        sb.AppendLine($"             var wrapped = new {wrapperClassName}();");

                        foreach (var parameter in parameters)
                        {
                            string typeName = parameter.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                            sb.AppendLine(
                                $"             wrapped.{parameter.Name} = ({typeName})parameters_{method.GetMethodSymbolSignature()}[\"{parameter.Name}\"];");
                        }

                        sb.AppendLine($"             return wrapped;");

                        sb.AppendLine("        }");
                        sb.AppendLine("");
                        sb.AppendLine(
                            $"        public void Populate(IReadOnlyDictionary<string, object> parameters_{method.GetMethodSymbolSignature()})");
                        sb.AppendLine("        {");
                        foreach (var parameter in parameters)
                        {
                            string typeName = parameter.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                            sb.AppendLine(
                                $"             {parameter.Name} = ({typeName})parameters_{method.GetMethodSymbolSignature()}[\"{parameter.Name}\"];");
                        }

                        sb.AppendLine("        }");
                        sb.AppendLine("");
                    }

                    if (parameters.Length > 0)
                    {
                        sb.AppendLine(
                            $"        public static ValueTask<{wrapperClassName}> BindAsync(HttpContext context, System.Reflection.ParameterInfo parameter)");
                        sb.AppendLine("        {");
                        sb.AppendLine($"            return ValueTask.FromResult(new {wrapperClassName}());");
                        sb.AppendLine("        }");
                    }

                    sb.AppendLine("    }");
                    sb.AppendLine();
                }
            }

            sb.AppendLine("}");
            var code = sb.ToString();
            spc.AddSource(fileName, SourceText.From(code, Encoding.UTF8));
        }
    }
}