using System.Collections.Generic;
using System.Linq;
using System.Text;
using Hubcon.Analyzers.SourceGenerators.Extensions;
using Hubcon.Analyzers.SourceGenerators.Models;
using HubconAnalyzers.SourceGenerators.Extensions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Hubcon.Analyzers.SourceGenerators.GeneratorCommands
{
    public static class GenerateHttpDelegates
    {
        public static void Execute(SourceProductionContext spc, IEnumerable<ControllerMetadata> controllers, string fileName)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("using System;");
            sb.AppendLine("using Microsoft.AspNetCore.Mvc;");
            sb.AppendLine("using System.Threading;");
            sb.AppendLine("using Hubcon;");
            sb.AppendLine();
            sb.AppendLine("namespace Hubcon.Generated");
            sb.AppendLine("{");
            sb.AppendLine($"    public static class EndpointDelegateProvider");
            sb.AppendLine("    {");
            sb.AppendLine("        public static Delegate? GetDelegate(string controller, string contractName, string signature)");
            sb.AppendLine("        {");
            sb.AppendLine("            var finalSignature = controller + \"_\" + contractName + \"_\" + signature;");
            sb.AppendLine("            switch(finalSignature)");
            sb.AppendLine("            {");

            foreach (var controller in controllers)
            {
                foreach (var endpoint in controller.Endpoints)
                {
                    var delegateName = $"{endpoint.FullName}_Delegate";
                    sb.AppendLine(
                        $"                 case \"{endpoint.Identifier}\": return EndpointDelegateProvider.{delegateName};");
                }
            }

            sb.AppendLine("                 default: return null;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");


            foreach (var controller in controllers)
            {
                foreach (var endpoint in controller.Endpoints)
                {
                    var delegateName =
                        $"{endpoint.FullName}_Delegate";
                    
                    var wrapperTypeName =
                        $"{endpoint.FullName}_Request";

                    sb.AppendLine();
                    sb.AppendLine($"        [System.Diagnostics.CodeAnalysis.DynamicDependency(System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.All, typeof(Microsoft.Extensions.Primitives.StringValues))]");

                    SymbolTools.MapMethodAttributes(endpoint, sb);
                    
                    if (endpoint.Parameters.Count(x => x.Type.ToDisplayString() != "System.Threading.CancellationToken") == 0)
                    {
                        sb.AppendLine($"        public static {endpoint.ControllerMethod.GetHubconResponseTypeFromMethod()} {delegateName}() => default!;");
                    }
                    else
                    {
                        sb.AppendLine($"        public static {endpoint.ControllerMethod.GetHubconResponseTypeFromMethod()} {delegateName}([AsParameters] {wrapperTypeName} request) => default!;");
                    }
                }
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
            var code = sb.ToString();
            spc.AddSource(fileName, SourceText.From(code, Encoding.UTF8));
        }
    }
}