using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Hubcon.Analyzers.SourceGenerators.GeneratorCommands
{
    public class GenerateControllerTypeProvider
    {
        public static void Execute(SourceProductionContext spc, IEnumerable<INamedTypeSymbol> controllers, string fileName)
        {
            // var sb = new StringBuilder();
            //
            // sb.AppendLine("// <auto-generated />");
            // sb.AppendLine("#nullable enable");
            // sb.AppendLine("using System;");
            // sb.AppendLine("using System.ComponentModel;");
            // sb.AppendLine("using System.Runtime.CompilerServices;");
            // sb.AppendLine("using System.Runtime.Serialization;");
            // sb.AppendLine("using System.Threading;");
            // sb.AppendLine("using System.Threading.Tasks;");
            // sb.AppendLine("using Microsoft.AspNetCore.Http;");
            // sb.AppendLine("using Microsoft.AspNetCore.Mvc.ModelBinding;");
            // sb.AppendLine();
            // sb.AppendLine("namespace Hubcon.Generated");
            // sb.AppendLine("{");
            //
            // sb.AppendLine($"    public static class Controller");
            // sb.AppendLine("    {");
            // sb.AppendLine(
            //     "        #if UNITY_2017_1_OR_NEWER\r\n        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad)]\r\n        #else\r\n        [ModuleInitializer]\r\n        #endif");
            // sb.AppendLine("        public static void Init()");
            // sb.AppendLine("        {");
            // sb.AppendLine(
            //     "             global::Hubcon.EndpointManager.Setup(EndpointDelegateProvider.GetDelegate, EndpointInvokerProvider.GetInvoker, ParameterWrapperProvider.GetWrapperType, ParameterWrapperProvider.GetWrapperDelegate);");
            // sb.AppendLine("        }");
            // sb.AppendLine();
            //
            // sb.AppendLine("        public static Type? GetControllerType(string contractName, string signature)");
            // sb.AppendLine("        {");
            // sb.AppendLine("            var finalSignature = contractName + \"_\" + signature;");
            // sb.AppendLine("            switch(finalSignature)");
            // sb.AppendLine("            {");
            // foreach (var interfaceSymbol in interfaces)
            // {
            //     var methods = interfaceSymbol.GetMembers()
            //         .OfType<IMethodSymbol>()
            //         .Where(m => m.MethodKind == MethodKind.Ordinary);
            //
            //
            //     foreach (var method in methods)
            //     {
            //         if (method.Parameters.Count(x => x.ToDisplayString() != "System.Threading.CancellationToken") == 0)
            //             continue;
            //
            //         var wrapperClassName =
            //             $"{interfaceSymbol.GetSafeName()}_{method.GetMethodSymbolSignature()}_Request";
            //
            //         sb.AppendLine(
            //             $"                 case \"{interfaceSymbol.Name}_{method.GetMethodSymbolSignature()}\": return typeof({wrapperClassName});");
            //     }
            // }
            //
            // sb.AppendLine("                 default: return null;");
            // sb.AppendLine("            }");
            // sb.AppendLine("        }");
            // sb.AppendLine("    }");
            // sb.AppendLine("}");
        }
    }
}