using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Hubcon.Analyzers.SourceGenerators.Extensions;
using Hubcon.Analyzers.SourceGenerators.Models;
using HubconAnalyzers.SourceGenerators.Extensions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Hubcon.Analyzers.SourceGenerators.GeneratorCommands
{
    public static class GenerateEndpointParameterWrappers
    {
        public static void Execute(SourceProductionContext spc, IEnumerable<ControllerMetadata> controllers, string fileName)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.ComponentModel;");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine("using System.Runtime.Serialization;");
            sb.AppendLine("using System.Threading;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine("using Microsoft.AspNetCore.Http;");
            sb.AppendLine("using Microsoft.AspNetCore.Mvc.ModelBinding;");
            sb.AppendLine();
            sb.AppendLine("namespace Hubcon.Generated");
            sb.AppendLine("{");

            sb.AppendLine($"    public static class ParameterWrapperProvider");
            sb.AppendLine("    {");
            sb.AppendLine(
                "        #if UNITY_2017_1_OR_NEWER\r\n        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad)]\r\n        #else\r\n        [ModuleInitializer]\r\n        #endif");
            sb.AppendLine("        public static void Init()");
            sb.AppendLine("        {");
            sb.AppendLine(
                "             global::Hubcon.EndpointManager.Setup(EndpointDelegateProvider.GetDelegate, EndpointInvokerProvider.GetInvoker, ParameterWrapperProvider.GetWrapperType, ParameterWrapperProvider.GetWrapperDelegate);");
            sb.AppendLine("        }");
            sb.AppendLine();

            sb.AppendLine("        public static Type? GetWrapperType(string controller, string contractName, string signature)");
            sb.AppendLine("        {");
            sb.AppendLine("            var finalSignature = controller + \"_\" + contractName + \"_\" + signature;");
            sb.AppendLine("            switch(finalSignature)");
            sb.AppendLine("            {");
            
            foreach (var controller in controllers)
            {
                foreach (var endpoint in controller.Endpoints)
                {
                    if (endpoint.Parameters.Count(x => x.Type.ToDisplayString() != "System.Threading.CancellationToken") == 0)
                        continue;
                    
                    var wrapperClassName =
                        $"{endpoint.FullName}_Request";

                    sb.AppendLine(
                        $"                 case \"{endpoint.Identifier}\": return typeof({wrapperClassName});");
                }
            }

            sb.AppendLine("                 default: return null;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");

            sb.AppendLine();

            sb.AppendLine(
                "        public static Func<IReadOnlyDictionary<string, object>, object>? GetWrapperDelegate(string controller, string contractName, string signature)");
            sb.AppendLine("        {");
            sb.AppendLine("            var finalSignature = controller + \"_\" + contractName + \"_\" + signature;");
            sb.AppendLine("            switch(finalSignature)");
            sb.AppendLine("            {");

            foreach (var controller in controllers)
            {
                foreach (var endpoint in controller.Endpoints)
                {
                    if (endpoint.Parameters.Count(x => x.Type.ToDisplayString() != "System.Threading.CancellationToken") == 0)
                        continue;
                    
                    var wrapperClassName =
                        $"{endpoint.FullName}_Request";

                    sb.AppendLine(
                        $"                 case \"{endpoint.Identifier}\":return {wrapperClassName}.GetWrapped;");
                }
            }

            sb.AppendLine("                 default: return null;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();

            foreach (var controller in controllers)
            {
                foreach (var endpoint in controller.Endpoints)
                {
                    if (endpoint.Parameters.Count(x => x.Type.ToDisplayString() != "System.Threading.CancellationToken") == 0)
                        continue;

                    var wrapperClassName =
                        $"{endpoint.FullName}_Request";

                    sb.AppendLine($"    public sealed class {wrapperClassName} : global::Hubcon.IWrapper");
                    sb.AppendLine("    {");
                    sb.AppendLine(
                        $"        [System.Diagnostics.CodeAnalysis.DynamicDependency(System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.All, typeof({wrapperClassName}))]");
                    sb.AppendLine(
                        $"        [System.Diagnostics.CodeAnalysis.DynamicDependency(System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors, typeof({wrapperClassName}))]");
                    sb.AppendLine($"        public {wrapperClassName}(){{ }}");
                    
                    SymbolTools.MapPropertyAttributes(endpoint, sb, true);

                    if (endpoint.Parameters.Count > 0)
                    {
                        sb.AppendLine(
                            $"        public static object GetWrapped(IReadOnlyDictionary<string, object> parameters_{endpoint.ControllerMethod.GetMethodSymbolSignature()})");
                        sb.AppendLine("        {");
                        sb.AppendLine($"             var wrapped = new {wrapperClassName}();");

                        foreach (var parameter in endpoint.Parameters)
                        {
                            if (parameter.Type.ToDisplayString() == "System.Threading.CancellationToken")
                                continue;
                            
                            string typeName = parameter.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                            sb.AppendLine(
                                $"             wrapped.{parameter.Name} = ({typeName})parameters_{endpoint.ControllerMethod.GetMethodSymbolSignature()}[\"{parameter.Name}\"];");
                        }

                        sb.AppendLine($"             return wrapped;");

                        sb.AppendLine("        }");
                        sb.AppendLine("");
                        sb.AppendLine(
                            $"        public void Populate(IReadOnlyDictionary<string, object> parameters_{endpoint.ControllerMethod.GetMethodSymbolSignature()})");
                        sb.AppendLine("        {");
                        foreach (var parameter in endpoint.Parameters)
                        {
                            if (parameter.Type.ToDisplayString() == "System.Threading.CancellationToken")
                                continue;
                            
                            string typeName = parameter.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                            sb.AppendLine(
                                $"             {parameter.Name} = ({typeName})parameters_{endpoint.ControllerMethod.GetMethodSymbolSignature()}[\"{parameter.Name}\"];");
                        }

                        sb.AppendLine("        }");
                        sb.AppendLine("");
                    }

                    if (endpoint.Parameters.Count > 0)
                    {
                        sb.AppendLine(
                            $"        public static ValueTask<{wrapperClassName}> BindAsync(HttpContext context, System.Reflection.ParameterInfo parameter)");
                        sb.AppendLine("        {");
                        sb.AppendLine($"            return ValueTask.FromResult(new {wrapperClassName}());");
                        sb.AppendLine("        }");
                    }

                    sb.AppendLine("    }");
                    sb.AppendLine();
                }
            }

            sb.AppendLine("}");
            var code = sb.ToString();
            spc.AddSource(fileName, SourceText.From(code, Encoding.UTF8));
        }
    }
}