using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Hubcon.Analyzers.SourceGenerators.Extensions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Hubcon.Analyzers.SourceGenerators.GeneratorCommands
{
    public static class GenerateMetadataResolver
    {
        public static void Execute(SourceProductionContext spc, string resolverName, ImmutableHashSet<ITypeSymbol> typesToSerialize, string fileName)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Text.Json;");
            sb.AppendLine("using System.Text.Json.Serialization.Metadata;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using Hubcon;");
            sb.AppendLine("using Hubcon.Shared.Abstractions.Attributes;");
            sb.AppendLine("using System.Threading;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine();
            sb.AppendLine($"namespace Hubcon.Generated {{");

            sb.AppendLine($"public class {resolverName} : IJsonTypeInfoResolver {{");
            sb.AppendLine($"    public static readonly {resolverName} Instance = new {resolverName}();");
            sb.AppendLine();

            sb.AppendLine("    public JsonTypeInfo GetTypeInfo(Type type, JsonSerializerOptions options) {");

            // Cambiamos el switch para que use comparaciones de Type directamente
            sb.AppendLine("        return type switch {");

            foreach (var type in typesToSerialize)
            {
                // Usamos el formato calificado completo (global::...) para el typeof
                var fullName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                var safeName = type.GetSafeName();

                // C# 8.0/Standard 2.1 syntax: Type t when t == typeof(...)
                sb.AppendLine($"            Type t when t == typeof({fullName}) => Create_{safeName}(options),");
            }

            // Caso especial para JsonElement
            sb.AppendLine(
                $"            Type t when t == typeof(global::System.Text.Json.JsonElement) => Create_System_Text_Json_JsonElement(options),");

            sb.AppendLine("            _ => null");
            sb.AppendLine("        };");
            sb.AppendLine("    }");

            List<string> methodNames = new List<string>();

            // Generar los métodos Create_{SafeName}
            foreach (var type in typesToSerialize)
            {
                var name = type.GetSafeName();

                if (methodNames.Any(x => x.ToLower() == name.ToLower()))
                    continue;

                methodNames.Add(name);
                GenerateTypeMetadataMethod(sb, type, optionsName: "options");
            }

            sb.AppendLine(@"
    private JsonTypeInfo Create_System_Text_Json_JsonElement(JsonSerializerOptions options)
    {
        return JsonMetadataServices.CreateValueInfo<global::System.Text.Json.JsonElement>(options, JsonMetadataServices.JsonElementConverter);
    }");

            sb.AppendLine("}"); // class
            sb.AppendLine("}"); // namespace

            var code = sb.ToString();
            spc.AddSource(fileName, SourceText.From(code, Encoding.UTF8));
        }
        
        private static void GenerateTypeMetadataMethod(StringBuilder sb, ITypeSymbol type, string optionsName)
        {
            var fullName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var safeName = type.GetSafeName();

            sb.AppendLine($"    private JsonTypeInfo Create_{safeName}(JsonSerializerOptions {optionsName}) {{");

            // Lógica específica para Nullables
            if (type.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T)
            {
                var innerType = (type as INamedTypeSymbol)?.TypeArguments.First();
                var innerFullName = innerType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                sb.AppendLine($@"
        var converter = JsonMetadataServices.GetNullableConverter<{innerFullName}>({optionsName});
        return JsonMetadataServices.CreateValueInfo<{fullName}>({optionsName}, converter);");
            }
            else
            {
                // 2. CASO ENUMS
                if (type.TypeKind == TypeKind.Enum)
                {
                    // Usamos el convertidor genérico que es 100% compatible con AOT
                    sb.AppendLine($@"
        var enumConverter = global::Hubcon.HubconEnumConverter<{fullName}>.Current;
        return JsonMetadataServices.CreateValueInfo<{fullName}>({optionsName}, enumConverter);");
                }
                else if (type.IsDictionary(out var keyType, out var valueType))
                {
                    var keyFullName = keyType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    var valueFullName = valueType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                    string creator = (type is INamedTypeSymbol n && !n.IsAbstract) ? $"() => new {fullName}()" : "null";

                    sb.AppendLine($@"
        var info = JsonMetadataServices.CreateIDictionaryInfo<{fullName}, {keyFullName}, {valueFullName}>(
            {optionsName},
            new JsonCollectionInfoValues<{fullName}> {{
                ObjectCreator = {creator},
                KeyInfo = {optionsName}.GetTypeInfo(typeof({keyFullName})),
                NumberHandling = default,
                SerializeHandler = null
            }}
        );
        return info;");
                }
                // 3. CASO COLECCIONES (List<T>, T[], etc.)
                else if (type.IsCollection(out var elementType))
                {
                    var elementFullName = elementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                    // Determinamos la implementación concreta para el ObjectCreator
                    string creator = "null";
                    if (type is IArrayTypeSymbol)
                    {
                        // Para arrays, el creador suele ser nulo o manejado internamente por STJ
                        creator = "null";
                    }
                    else if (type.TypeKind == TypeKind.Class && !type.IsAbstract)
                    {
                        creator = $"() => new {fullName}()";
                    }

                    sb.AppendLine($@"
        var info = JsonMetadataServices.CreateIEnumerableInfo<{fullName}, {elementFullName}>(
            {optionsName}, 
            new JsonCollectionInfoValues<{fullName}> {{
                ObjectCreator = {creator},
                KeyInfo = null,
                ElementInfo = {optionsName}.GetTypeInfo(typeof({elementFullName})),
                NumberHandling = default,
                SerializeHandler = null // STJ lo resuelve internamente si ElementInfo es válido
            }}
        );
        return info;");
                }
                else
                {
                    sb.AppendLine(
                        $"        var info = JsonMetadataServices.CreateObjectInfo<{fullName}>({optionsName}, new JsonObjectInfoValues<{fullName}> {{");

                    var namedType = type as INamedTypeSymbol;

                    var constructor = namedType?.Constructors
                        .OrderByDescending(c => c.Parameters.Length)
                        .FirstOrDefault(c =>
                            c.DeclaredAccessibility == Accessibility.Public
                            && c.GetAttributes().Any(a =>
                                a.AttributeClass?.ToDisplayString() ==
                                "System.Text.Json.Serialization.JsonConstructorAttribute"));

                    if (constructor == null)
                    {
                        constructor = namedType?.Constructors
                            .OrderByDescending(c => c.Parameters.Length)
                            .FirstOrDefault(c => c.DeclaredAccessibility == Accessibility.Public);
                    }

                    // Si el constructor tiene punteros, lo ignoramos por completo
                    bool hasPointers = constructor?.Parameters.Any(p => p.Type.TypeKind == TypeKind.Pointer) ?? false;

                    if (constructor != null && constructor.Parameters.Length > 0 && !hasPointers)
                    {
                        sb.AppendLine(
                            "            ConstructorParameterMetadataInitializer = () => new JsonParameterInfoValues[] {");
                        foreach (var p in constructor.Parameters)
                        {
                            var pType = p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                            sb.AppendLine($@"                new JsonParameterInfoValues {{ 
                    Name = ""{p.Name}"", 
                    ParameterType = typeof({pType}), 
                    Position = {p.Ordinal} 
                }},");
                        }

                        sb.AppendLine("            },");

                        var args = string.Join(", ",
                            constructor.Parameters.Select((p, i) =>
                                $"({p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)})args[{i}]"));
                        sb.AppendLine(
                            $"            ObjectWithParameterizedConstructorCreator = (args) => new {fullName}({args}),");
                    }
                    else if (namedType != null && !namedType.IsAbstract)
                    {
                        sb.AppendLine($"            ObjectCreator = () => new {fullName}(),");
                    }

                    // --- LÓGICA DE PROPIEDADES ---
                    sb.AppendLine("            PropertyMetadataInitializer = (context) => new JsonPropertyInfo[] {");
                    foreach (var prop in type.GetMembers().OfType<IPropertySymbol>()
                                 .Where(p => p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic))
                    {
                        // 1. Soporte para [JsonIgnore]
                        var isIgnored = prop.GetAttributes().Any(a =>
                            a.AttributeClass?.ToDisplayString() ==
                            "System.Text.Json.Serialization.JsonIgnoreAttribute");

                        if (isIgnored) continue;

                        // 2. Soporte para [JsonPropertyName("...")]
                        var jsonNameAttr = prop.GetAttributes().FirstOrDefault(a =>
                            a.AttributeClass?.ToDisplayString() ==
                            "System.Text.Json.Serialization.JsonPropertyNameAttribute");

                        // Si tiene el atributo usamos el valor definido, si no, el nombre de la propiedad en C#
                        string jsonPropertyName =
                            jsonNameAttr?.ConstructorArguments.FirstOrDefault().Value?.ToString() ?? prop.Name;

                        var pType = prop.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                        sb.AppendLine(
                            $"                JsonMetadataServices.CreatePropertyInfo<{pType}>({optionsName}, new JsonPropertyInfoValues<{pType}> {{");
                        sb.AppendLine(
                            $"                    PropertyName = \"{prop.Name}\","); // Nombre real en el código C#
                        sb.AppendLine(
                            $"                    JsonPropertyName = \"{jsonPropertyName}\","); // Nombre que aparecerá en el JSON
                        sb.AppendLine($"                    Getter = (obj) => (({fullName})obj).{prop.Name},");
                        sb.AppendLine(
                            $"                    PropertyTypeInfo = {optionsName}.GetTypeInfo(typeof({pType})),");
                        sb.AppendLine($"                    DeclaringType = typeof({fullName}),");
                        sb.AppendLine($"                    IsProperty = true,");
                        sb.AppendLine($"                    IsPublic = true,");

                        bool canSet = !prop.IsReadOnly && (prop.SetMethod == null || !prop.SetMethod.IsInitOnly);
                        if (canSet)
                            sb.AppendLine(
                                $"                    Setter = (obj, val) => (({fullName})obj).{prop.Name} = val,");

                        sb.AppendLine("                }),");
                    }

                    sb.AppendLine("            }");
                    sb.AppendLine("        });");
                    sb.AppendLine("        return info;");
                }
            }

            sb.AppendLine("    }");
        }
    }
}