using System.Collections.Generic;
using System.Text;
using Hubcon.Analyzers.SourceGenerators.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Hubcon.Analyzers.SourceGenerators.GeneratorCommands
{
    public class GenerateTaskUnwrappers
    {
        public static void Execute(SourceProductionContext spc, IEnumerable<ControllerMetadata> controllers, string fileName)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine("using Hubcon;");
            sb.AppendLine();
            sb.AppendLine("namespace Hubcon.Generated");
            sb.AppendLine("{");
            
            var taskReturnTypes = new Dictionary<string, ITypeSymbol>();

            foreach (var controller in controllers)
            {
                foreach (var endpoint in controller.Endpoints)
                {
                    var returnType = endpoint.ControllerMethod.ReturnType;

                    if (returnType is INamedTypeSymbol namedType &&
                        namedType.IsGenericType &&
                        namedType.ConstructedFrom.ToDisplayString().StartsWith("System.Threading.Tasks.Task<"))
                    {
                        var innerType = namedType.TypeArguments[0];
                        var innerTypeKey = innerType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                        if (!taskReturnTypes.ContainsKey(innerTypeKey))
                        {
                            taskReturnTypes.Add(innerTypeKey, innerType);
                        }
                    }
                }
            }

            sb.AppendLine("    public static class HubconTaskUnwrapperRegistry");
            sb.AppendLine("    {");
            sb.AppendLine("        [ModuleInitializer]");
            sb.AppendLine("        public static void Init()");
            sb.AppendLine("        {");

            sb.AppendLine($"            var map = new Dictionary<Type, Func<Task, object?>>({taskReturnTypes.Count});");
            sb.AppendLine();

            foreach (var kvp in taskReturnTypes)
            {
                var typeDisplay = kvp.Value.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                var safeMethodName = kvp.Value.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat)
                    .Replace(".", "_").Replace("<", "_").Replace(">", "_");

                sb.AppendLine($"            map.Add(typeof({typeDisplay}), Extract_{safeMethodName});");
            }

            sb.AppendLine();
            sb.AppendLine("            global::Hubcon.TaskUnwrapperRegistry.Setup(map);");
            sb.AppendLine("        }");
            
            foreach (var kvp in taskReturnTypes)
            {
                var typeDisplay = kvp.Value.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                var safeMethodName = kvp.Value.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat)
                    .Replace(".", "_").Replace("<", "_").Replace(">", "_");

                sb.AppendLine();
                sb.AppendLine($"        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
                sb.AppendLine($"        private static object Extract_{safeMethodName}(Task task)");
                sb.AppendLine("        {");
                sb.AppendLine($"            return ((Task<{typeDisplay}>)task).Result;");
                sb.AppendLine("        }");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            var code = sb.ToString();
            spc.AddSource(fileName, SourceText.From(code, Encoding.UTF8));
        }
    }
}