using System.Collections.Generic;
using System.Linq;
using System.Text;
using Hubcon.Analyzers.SourceGenerators.Extensions;
using HubconAnalyzers.SourceGenerators.Extensions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Hubcon.Analyzers.SourceGenerators.GeneratorCommands
{
    public static class GenerateDedicatedInvokers
    {
        public static void Execute(SourceProductionContext spc, IEnumerable<INamedTypeSymbol> interfaces, string fileName)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Threading;");
            sb.AppendLine("using Hubcon;");
            sb.AppendLine();
            sb.AppendLine("namespace Hubcon.Generated");
            sb.AppendLine("{");

            sb.AppendLine($"    public static class EndpointInvokerProvider");
            sb.AppendLine("    {");
            sb.AppendLine("        public static IEndpointInvoker GetInvoker(string contractName, string signature)");
            sb.AppendLine("        {");
            sb.AppendLine("            var finalSignature = contractName + \"_\" + signature;");
            sb.AppendLine("            switch(finalSignature)");
            sb.AppendLine("            {");

            foreach (var interfaceSymbol in interfaces)
            {
                var methods = interfaceSymbol.GetMembers()
                    .OfType<IMethodSymbol>()
                    .Where(m => m.MethodKind == MethodKind.Ordinary);

                foreach (var method in methods)
                {
                    var invokerClassName =
                        $"{interfaceSymbol.GetSafeName()}_{method.GetMethodSymbolSignature()}_Invoker";
                    sb.AppendLine(
                        $"                 case \"{interfaceSymbol.Name}_{method.GetMethodSymbolSignature()}\": return new {invokerClassName}();");
                }
            }

            sb.AppendLine("                 default: return null;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();


            foreach (var interfaceSymbol in interfaces)
            {
                var methods = interfaceSymbol.GetMembers()
                    .OfType<IMethodSymbol>()
                    .Where(m => m.MethodKind == MethodKind.Ordinary);

                foreach (var method in methods)
                {
                    var invokerClassName =
                        $"{interfaceSymbol.GetSafeName()}_{method.GetMethodSymbolSignature()}_Invoker";
                    var wrapperTypeName =
                        $"{interfaceSymbol.GetSafeName()}_{method.GetMethodSymbolSignature()}_Request";
                    var controllerTypeName = interfaceSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                    sb.AppendLine($"    public sealed class {invokerClassName} : IEndpointInvoker");
                    sb.AppendLine("    {");
                    sb.AppendLine("        public object Invoke(object target, object wrapper, CancellationToken ct)");
                    sb.AppendLine("        {");

                    // Casteo directo y local del target
                    sb.AppendLine($"            var typedTarget = ({controllerTypeName})target;");

                    // Chequeamos si tiene parámetros que requieran usar el wrapper
                    bool hasRealParameters = false;
                    foreach (var param in method.Parameters)
                    {
                        if (param.Type.ToDisplayString() != "System.Threading.CancellationToken")
                        {
                            hasRealParameters = true;
                            break;
                        }
                    }

                    // Solo casteamos el wrapper si realmente se espera que exista un objeto con datos
                    if (hasRealParameters)
                    {
                        sb.AppendLine(
                            $"            var typedWrapper = (global::Hubcon.Generated.{wrapperTypeName})wrapper;");
                    }

                    sb.AppendLine();

                    // Mapeo de parámetros
                    var paramList = new List<string>();
                    foreach (var param in method.Parameters)
                    {
                        if (param.Type.ToDisplayString() == "System.Threading.CancellationToken")
                        {
                            paramList.Add("ct");
                        }
                        else
                        {
                            // Si llegamos acá, sabemos que 'typedWrapper' fue declarado arriba
                            paramList.Add($"typedWrapper.{param.Name}");
                        }
                    }

                    string argsStr = string.Join(", ", paramList);

                    if (method.ReturnsVoid)
                    {
                        sb.AppendLine($"            typedTarget.{method.Name}({argsStr});");
                        sb.AppendLine("            return null;");
                    }
                    else
                    {
                        sb.AppendLine($"            return (object)typedTarget.{method.Name}({argsStr});");
                    }

                    sb.AppendLine("        }");
                    sb.AppendLine("    }");
                    sb.AppendLine();
                }
            }

            sb.AppendLine("}");
            var code = sb.ToString();
            spc.AddSource(fileName, SourceText.From(code, Encoding.UTF8));
        }
    }
}