using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Hubcon.Analyzers.SourceGenerators.GeneratorCommands;

public static class GenerateValidatorNodes
{
    public static void Execute(
        SourceProductionContext spc,
        ImmutableArray<INamedTypeSymbol> markedTypesToValidate,
        ImmutableHashSet<ITypeSymbol> typesToValidateFromContracts,
        string generatedClassName,
        string generatedFileName)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.ComponentModel.DataAnnotations;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine();
        sb.AppendLine("namespace Hubcon.Generated");
        sb.AppendLine("{");
        sb.AppendLine($"    public static class {generatedClassName}");
        sb.AppendLine("    {");

        // Unificar y deduplicar — marked tiene prioridad pero el set final es uno solo
        var allRootTypes = new HashSet<ITypeSymbol>(SymbolEqualityComparer.Default);
        foreach (var t in markedTypesToValidate) allRootTypes.Add(t);
        foreach (var t in typesToValidateFromContracts) allRootTypes.Add(t);

        // emitted mantiene el orden de inserción (bottom-up) → correcto para
        // la inicialización de campos estáticos y para el lookup dictionary
        var emitted = new Dictionary<ITypeSymbol, string>(SymbolEqualityComparer.Default);
        var visited = new HashSet<ITypeSymbol>(SymbolEqualityComparer.Default);

        foreach (var type in allRootTypes)
            ValidatorTools.CollectAndEmitValidators(sb, type, "        ", visited, emitted, forceEmit: true);

        // ── Lookup dictionary (O(1) por tipo) ────────────────────────────────
        // Los campos estáticos se inicializan en orden de declaración,
        // y emitted está en orden bottom-up → hijos siempre antes que padres
        sb.AppendLine();
        sb.AppendLine("        private static readonly Dictionary<Type, object> _lookup = new()");
        sb.AppendLine("        {");
        foreach (var item in emitted)
        {
            var type = item.Key;
            var fieldName = item.Value.TrimEnd('?');
            var q = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            sb.AppendLine($"            [typeof({q})] = {fieldName},");
        }

        sb.AppendLine("        };");

        // GetNodeValidator
        sb.AppendLine();
        sb.AppendLine("        public static object? GetNodeValidator(Type type) =>");
        sb.AppendLine("            _lookup.TryGetValue(type, out var node) ? node : null;");

        // Init
        sb.AppendLine();
        sb.AppendLine("        #if UNITY_2017_1_OR_NEWER");
        sb.AppendLine(
            "        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad)]");
        sb.AppendLine("        #else");
        sb.AppendLine("        [ModuleInitializer]");
        sb.AppendLine("        #endif");
        sb.AppendLine("        public static void Init()");
        sb.AppendLine("        {");
        sb.AppendLine("            global::Hubcon.Validation.NodeValidatorProvider.Setup(GetNodeValidator);");
        sb.AppendLine("        }");

        sb.AppendLine("    }");
        sb.AppendLine("}");

        spc.AddSource(generatedFileName, SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}