using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Hubcon.Analyzers.SourceGenerators.Extensions;
using Hubcon.Analyzers.SourceGenerators.Models;
using HubconAnalyzers.SourceGenerators.Extensions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Hubcon.Analyzers.SourceGenerators.GeneratorCommands
{
    public static class GenerateEndpointParameterWrappers
    {
        public static void Execute(SourceProductionContext spc, IEnumerable<ControllerMetadata> controllers,
            string fileName)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Reflection;");
            sb.AppendLine("using System.Collections.Immutable;");
            sb.AppendLine("using System.ComponentModel;");
            sb.AppendLine("using System.ComponentModel.DataAnnotations;");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine("using System.Runtime.Serialization;");
            sb.AppendLine("using System.Threading;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine("using Microsoft.AspNetCore.Http;");
            sb.AppendLine("using Microsoft.AspNetCore.Mvc.ModelBinding;");
            sb.AppendLine();
            sb.AppendLine("namespace Hubcon.Generated");
            sb.AppendLine("{");

            sb.AppendLine($"    public static class ParameterWrapperProvider");
            sb.AppendLine("    {");
            sb.AppendLine(
                "        #if UNITY_2017_1_OR_NEWER\r\n        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad)]\r\n        #else\r\n        [ModuleInitializer]\r\n        #endif");
            sb.AppendLine("        public static void Init()");
            sb.AppendLine("        {");
            sb.AppendLine(
                "             global::Hubcon.EndpointManager.Setup(EndpointDelegateProvider.GetDelegate, EndpointInvokerProvider.GetInvoker, ParameterWrapperProvider.GetWrapperType, ParameterWrapperProvider.GetWrapperDelegate);");
            sb.AppendLine("        }");
            sb.AppendLine();

            sb.AppendLine(
                "        public static Type? GetWrapperType(string controller, string contractName, string signature)");
            sb.AppendLine("        {");
            sb.AppendLine("            var finalSignature = controller + \"_\" + contractName + \"_\" + signature;");
            sb.AppendLine("            switch(finalSignature)");
            sb.AppendLine("            {");

            foreach (var controller in controllers)
            {
                foreach (var endpoint in controller.Endpoints)
                {
                    if (endpoint.Parameters.Count(x =>
                            x.Type.ToDisplayString() != "System.Threading.CancellationToken") == 0)
                        continue;

                    var wrapperClassName =
                        $"{endpoint.FullName}_Request";

                    sb.AppendLine(
                        $"                 case \"{endpoint.Identifier}\": return typeof({wrapperClassName});");
                }
            }

            sb.AppendLine("                 default: return null;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");

            sb.AppendLine();

            sb.AppendLine(
                "        public static Func<IReadOnlyDictionary<string, object>, object>? GetWrapperDelegate(string controller, string contractName, string signature)");
            sb.AppendLine("        {");
            sb.AppendLine("            var finalSignature = controller + \"_\" + contractName + \"_\" + signature;");
            sb.AppendLine("            switch(finalSignature)");
            sb.AppendLine("            {");

            foreach (var controller in controllers)
            {
                foreach (var endpoint in controller.Endpoints)
                {
                    if (endpoint.Parameters.Count(x =>
                            x.Type.ToDisplayString() != "System.Threading.CancellationToken") == 0)
                        continue;

                    var wrapperClassName =
                        $"{endpoint.FullName}_Request";

                    sb.AppendLine(
                        $"                 case \"{endpoint.Identifier}\":return {wrapperClassName}.GetWrapped;");
                }
            }

            sb.AppendLine("                 default: return null;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();

            foreach (var controller in controllers)
            {
                foreach (var endpoint in controller.Endpoints)
                {
                    if (endpoint.Parameters.Count(x =>
                            x.Type.ToDisplayString() != "System.Threading.CancellationToken") == 0)
                        continue;

                    var wrapperClassName =
                        $"{endpoint.FullName}_Request";

                    sb.AppendLine($"    public sealed class {wrapperClassName} : global::Hubcon.IWrapper");
                    sb.AppendLine("    {");
                    sb.AppendLine(
                        $"        [System.Diagnostics.CodeAnalysis.DynamicDependency(System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.All, typeof({wrapperClassName}))]");
                    sb.AppendLine(
                        $"        [System.Diagnostics.CodeAnalysis.DynamicDependency(System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors, typeof({wrapperClassName}))]");
                    sb.AppendLine($"        public {wrapperClassName}(){{ }}");

                    SymbolTools.MapPropertyAttributes(endpoint, wrapperClassName, sb, true);

                    if (endpoint.Parameters.Count > 0)
                    {
                        sb.AppendLine(
                            $"        public static object GetWrapped(IReadOnlyDictionary<string, object> parameters_{endpoint.ControllerMethod.GetMethodSymbolSignature()})");
                        sb.AppendLine("        {");
                        sb.AppendLine($"             var wrapped = new {wrapperClassName}();");

                        foreach (var parameter in endpoint.Parameters)
                        {
                            if (parameter.Type.ToDisplayString() == "System.Threading.CancellationToken")
                                continue;

                            string typeName = parameter.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                            sb.AppendLine(
                                $"             wrapped.{parameter.Name} = ({typeName})parameters_{endpoint.ControllerMethod.GetMethodSymbolSignature()}[\"{parameter.Name}\"];");
                        }

                        sb.AppendLine($"             return wrapped;");

                        sb.AppendLine("        }");
                        sb.AppendLine("");
                        sb.AppendLine(
                            $"        public void Populate(IReadOnlyDictionary<string, object> parameters_{endpoint.ControllerMethod.GetMethodSymbolSignature()})");
                        sb.AppendLine("        {");
                        foreach (var parameter in endpoint.Parameters)
                        {
                            if (parameter.Type.ToDisplayString() == "System.Threading.CancellationToken")
                                continue;

                            string typeName = parameter.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                            sb.AppendLine(
                                $"             {parameter.Name} = ({typeName})parameters_{endpoint.ControllerMethod.GetMethodSymbolSignature()}[\"{parameter.Name}\"];");
                        }

                        sb.AppendLine("        }");
                        sb.AppendLine("");
                    }

                    if (endpoint.Parameters.Count > 0)
                    {
                        sb.AppendLine(
                            $"        public static ValueTask<{wrapperClassName}> BindAsync(HttpContext context, System.Reflection.ParameterInfo parameter)");
                        sb.AppendLine("        {");
                        sb.AppendLine($"            return ValueTask.FromResult(new {wrapperClassName}());");
                        sb.AppendLine("        }");
                    }

                    if (endpoint.Parameters.Count > 0)
                    {
                        var attributePropertiesSb = new StringBuilder();

                        sb.AppendLine();
                        sb.AppendLine(
                            "        public bool TryValidate(out List<System.ComponentModel.DataAnnotations.ValidationResult> errors)");
                        sb.AppendLine("        {");
                        sb.AppendLine(
                            "            errors = new List<System.ComponentModel.DataAnnotations.ValidationResult>();");
                        sb.AppendLine(
                            $"            var context = new System.ComponentModel.DataAnnotations.ValidationContext(this, nameof({wrapperClassName}), null, null);");
                        sb.AppendLine();

                        foreach (var parameter in endpoint.Parameters)
                        {
                            if (parameter.Type.ToDisplayString() == "System.Threading.CancellationToken")
                                continue;

                            string paramAccessPath = $"{parameter.Name}";
                            string paramMemberName = parameter.Name;

                            sb.AppendLine(
                                $"            Validator.TryValidateValue({paramAccessPath}, new ValidationContext(this) {{ MemberName = nameof({parameter.Name}) }}, errors, {parameter.Name}_attributes);");

                            var visitedTypes = new HashSet<ITypeSymbol>(SymbolEqualityComparer.Default);
                            EmitChildPropertiesValidation(
                                sb,
                                attributePropertiesSb,
                                paramAccessPath,
                                parameter.Type,
                                paramMemberName,
                                visitedTypes);
                        }

                        sb.AppendLine();
                        sb.AppendLine("            return errors.Count == 0;");
                        sb.AppendLine("        }");

                        sb.AppendLine();
                        sb.AppendLine(attributePropertiesSb.ToString());
                    }

                    sb.AppendLine("    }");
                    sb.AppendLine();
                }
            }

            sb.AppendLine("}");
            var code = sb.ToString();
            spc.AddSource(fileName, SourceText.From(code, Encoding.UTF8));
        }

        private static void EmitChildPropertiesValidation(
            StringBuilder validateMethodSb,
            StringBuilder attributePropertiesSb,
            string parentAccessPath,
            ITypeSymbol typeSymbol,
            string parentMemberName,
            HashSet<ITypeSymbol> visitedTypes,
            int indentLevel = 3)
        {
            if (typeSymbol == null ||
                typeSymbol.SpecialType != SpecialType.None ||
                !visitedTypes.Add(typeSymbol))
            {
                return;
            }

            if (typeSymbol.TypeKind != TypeKind.Class && typeSymbol.TypeKind != TypeKind.Struct)
            {
                return;
            }

            string indent = new string(' ', indentLevel * 4);
            string innerIndent = new string(' ', (indentLevel + 1) * 4);

            var eligibleProperties = typeSymbol.GetMembers()
                .OfType<IPropertySymbol>()
                .Where(p => !p.IsStatic &&
                            p.DeclaredAccessibility == Accessibility.Public &&
                            !p.IsIndexer &&
                            !p.GetAttributes().Any(a => a.AttributeClass?.Name == "JsonIgnoreAttribute") &&
                            !IsPrimitiveOrNullablePrimitive(p.Type)) // <--- FILTRO DE PRIMITIVOS Y NULLABLE PRIMITIVOS
                .ToList();

            if (eligibleProperties.Count == 0) return;

            validateMethodSb.AppendLine($"{indent}if ({parentAccessPath} != null)");
            validateMethodSb.AppendLine($"{indent}{{");

            foreach (var prop in eligibleProperties)
            {
                string currentAccessPath = $"{parentAccessPath}.{prop.Name}";
                string currentMemberName = $"{parentMemberName}.{prop.Name}";
                string attributePropName = $"{currentMemberName.Replace('.', '_')}_attributes";
                string typeDisplay = prop.ContainingType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                attributePropertiesSb.AppendLine(
                    $"        private static System.ComponentModel.DataAnnotations.ValidationAttribute[] {attributePropName} =>");
                attributePropertiesSb.AppendLine(
                    $"            (typeof({typeDisplay}).GetProperty(nameof({typeDisplay}.{prop.Name}))?.GetCustomAttributes(typeof(System.ComponentModel.DataAnnotations.ValidationAttribute), true) as System.ComponentModel.DataAnnotations.ValidationAttribute[]) is {{ Length: > 0 }} attrs");
                attributePropertiesSb.AppendLine($"                ? attrs");
                attributePropertiesSb.AppendLine(
                    $"                : new System.ComponentModel.DataAnnotations.ValidationAttribute[] {{ new global::System.Diagnostics.CodeAnalysis.Validation.ValidateObjectAttribute() }};");
                attributePropertiesSb.AppendLine();

                // Validar el valor
                validateMethodSb.AppendLine(
                    $"{innerIndent}Validator.TryValidateValue({currentAccessPath}, new ValidationContext({parentAccessPath}) {{ MemberName = \"{currentMemberName}\" }}, errors, {attributePropName});");

                // Continuar recursión
                EmitChildPropertiesValidation(
                    validateMethodSb,
                    attributePropertiesSb,
                    currentAccessPath,
                    prop.Type,
                    currentMemberName,
                    visitedTypes,
                    indentLevel + 1);
            }

            validateMethodSb.AppendLine($"{indent}}}");
        }

// Método auxiliar para detectar primitivos, enums y sus equivalentes en Nullable<T>
        private static bool IsPrimitiveOrNullablePrimitive(ITypeSymbol typeSymbol)
        {
            if (typeSymbol == null) return true;

            // Primitivos directos, string, decimal, DateTime, etc. o Enums
            if (typeSymbol.SpecialType != SpecialType.None || typeSymbol.TypeKind == TypeKind.Enum)
            {
                return true;
            }

            // Nullable<T> de un primitivo, enum o struct conocido
            if (typeSymbol is INamedTypeSymbol
                {
                    OriginalDefinition.SpecialType: SpecialType.System_Nullable_T
                } nullableType)
            {
                var underlyingType = nullableType.TypeArguments.FirstOrDefault();
                if (underlyingType != null)
                {
                    return underlyingType.SpecialType != SpecialType.None || underlyingType.TypeKind == TypeKind.Enum;
                }
            }

            return false;
        }
    }
}