using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Hubcon.Analyzers.SourceGenerators.GeneratorCommands
{
    public class GenerateProxyRegistry
    {
        public static void Execute(SourceProductionContext spc, IEnumerable<INamedTypeSymbol> interfaces, string fileName)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Runtime.CompilerServices;"); // Necesario para ModuleInitializer
            sb.AppendLine("using System.Diagnostics.CodeAnalysis;");
            sb.AppendLine("");
            sb.AppendLine("namespace Hubcon.Generated");
            sb.AppendLine("{");
            sb.AppendLine("    public static partial class ProxyLookup");
            sb.AppendLine("    {");
            sb.AppendLine("        /// <summary>");
            sb.AppendLine("        /// Inicializa automáticamente el lookup de proxies en el framework.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine(
                "        #if UNITY_2017_1_OR_NEWER\r\n        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad)]\r\n        #else\r\n        [ModuleInitializer]\r\n        #endif");
            sb.AppendLine("        public static void Initialize()");
            sb.AppendLine("        {");
            sb.AppendLine("            // Pasamos el método como Func<Type, Type?> al framework");
            sb.AppendLine("            Hubcon.Client.Builder.HubconClientBuilder.SetupProxyLookup(GetProxyType);");
            sb.AppendLine("        }");
            sb.AppendLine("");
            sb.AppendLine("        [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(ProxyLookup))]");
            sb.AppendLine("        public static Type? GetProxyType(Type interfaceType)");
            sb.AppendLine("        {");
            // Usamos FullName o AssemblyQualifiedName para evitar colisiones entre proyectos
            sb.AppendLine("            return interfaceType.FullName switch");
            sb.AppendLine("            {");

            foreach (var interfaceSymbol in interfaces)
            {
                // Usamos ToDisplayString sin global:: para el string del switch, 
                // pero typeof() sí necesita el path completo.
                string interfaceFullName = interfaceSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                    .Replace("global::", "");
                string proxyFullPath =
                    $"{interfaceSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}Proxy";

                sb.AppendLine($"                \"{interfaceFullName}\" => typeof({proxyFullPath}),");
            }

            sb.AppendLine("                _ => null");
            sb.AppendLine("            };");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            var code = sb.ToString();
            spc.AddSource(fileName, SourceText.From(code, Encoding.UTF8));
        }
    }
}