using System.Collections.Generic;
using System.Linq;
using System.Text;
using Hubcon.Analyzers.SourceGenerators.Extensions;
using Hubcon.Analyzers.SourceGenerators.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Hubcon.Analyzers.SourceGenerators.GeneratorCommands
{
    public class GenerateControllerTypeProvider
    {
        public static void Execute(SourceProductionContext spc, IEnumerable<ControllerMetadata> pairs, string fileName)
        {
            var sb = new StringBuilder();
            
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Frozen;");
            sb.AppendLine("using System.ComponentModel;");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine("using System.Runtime.Serialization;");
            sb.AppendLine("using System.Threading;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine();
            sb.AppendLine("namespace Hubcon.Generated");
            sb.AppendLine("{");
            sb.AppendLine($"    public static class ControllerMetadataProvider");
            sb.AppendLine("    {");
            sb.AppendLine(
                "        #if UNITY_2017_1_OR_NEWER\r\n        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad)]\r\n        #else\r\n        [ModuleInitializer]\r\n        #endif");
            sb.AppendLine("        public static void Init()");
            sb.AppendLine("        {");
            sb.AppendLine("             var controllers = new Dictionary<string, Type>()");
            sb.AppendLine("             {");

            var controllersArray = pairs.ToArray();
            var count = controllersArray.Length;
            for(var i = 0; i < count; i++)
            {
                sb.AppendLine(i == count - 1
                    ? $"                {{\"{controllersArray[i].Controller.ToDisplayString()}\", typeof({controllersArray[i].Controller.ToDisplayString()})}}"
                    : $"                {{\"{controllersArray[i].Controller.ToDisplayString()}\", typeof({controllersArray[i].Controller.ToDisplayString()})}},");
            }
            
            sb.AppendLine("             };");
            sb.AppendLine("             Hubcon.Server.Core.EndpointManagement.ControllerMetadata.Setup(controllers.ToFrozenDictionary());");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            var code = sb.ToString();
            spc.AddSource(fileName, SourceText.From(code, Encoding.UTF8));
        }
    }
}