using System.Collections.Generic;
using System.Linq;
using System.Text;
using Hubcon.Analyzers.SourceGenerators.Extensions;
using HubconAnalyzers.SourceGenerators.Extensions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Hubcon.Analyzers.SourceGenerators.GeneratorCommands
{
    public static class GenerateHttpDelegates
    {
        public static void Execute(SourceProductionContext spc, IEnumerable<INamedTypeSymbol> interfaces, string fileName)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("using System;");
            sb.AppendLine("using Microsoft.AspNetCore.Mvc;");
            sb.AppendLine("using System.Threading;");
            sb.AppendLine("using Hubcon;");
            sb.AppendLine();
            sb.AppendLine("namespace Hubcon.Generated");
            sb.AppendLine("{");
            sb.AppendLine($"    public static class EndpointDelegateProvider");
            sb.AppendLine("    {");
            sb.AppendLine("        public static Delegate? GetDelegate(string contractName, string signature)");
            sb.AppendLine("        {");
            sb.AppendLine("            var finalSignature = contractName + \"_\" + signature;");
            sb.AppendLine("            switch(finalSignature)");
            sb.AppendLine("            {");

            foreach (var interfaceSymbol in interfaces)
            {
                var methods = interfaceSymbol.GetMembers()
                    .OfType<IMethodSymbol>()
                    .Where(m => m.MethodKind == MethodKind.Ordinary);

                foreach (var method in methods)
                {
                    var delegateName = $"{interfaceSymbol.GetSafeName()}_{method.GetMethodSymbolSignature()}_Delegate";
                    sb.AppendLine(
                        $"                 case \"{interfaceSymbol.Name}_{method.GetMethodSymbolSignature()}\": return EndpointDelegateProvider.{delegateName};");
                }
            }

            sb.AppendLine("                 default: return null;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");


            foreach (var interfaceSymbol in interfaces)
            {
                var methods = interfaceSymbol.GetMembers()
                    .OfType<IMethodSymbol>()
                    .Where(m => m.MethodKind == MethodKind.Ordinary);

                foreach (var method in methods)
                {
                    var delegateName =
                        $"{interfaceSymbol.GetSafeName()}_{method.GetMethodSymbolSignature()}_Delegate";
                    
                    var wrapperTypeName =
                        $"{interfaceSymbol.GetSafeName()}_{method.GetMethodSymbolSignature()}_Request";

                    sb.AppendLine($"        [System.Diagnostics.CodeAnalysis.DynamicDependency(System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.All, typeof(Microsoft.Extensions.Primitives.StringValues))]");

                    
                    if (method.Parameters.Count(x => x.Type.ToDisplayString() != "System.Threading.CancellationToken") == 0)
                    {
                        sb.AppendLine($"        public static {method.GetHubconResponseTypeFromMethod()} {delegateName}() => default!;");
                    }
                    else
                    {
                        sb.AppendLine($"        public static {method.GetHubconResponseTypeFromMethod()} {delegateName}([AsParameters] {wrapperTypeName} request) => default!;");
                    }
                }
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
            var code = sb.ToString();
            spc.AddSource(fileName, SourceText.From(code, Encoding.UTF8));
        }
        
    }
}