////Generated by Hubcon.Analyzers.SourceGenerators v1.0.0-rc1 at 9/1/2026 00:37:48

//#nullable enable
//using Hubcon.Client.Core.Proxies;
//using Hubcon.Shared.Abstractions.Models;
//using Hubcon.Shared.Abstractions.Standard.Interceptor;
//using Hubcon.Shared.Abstractions.Standard.Interfaces;
//using Hubcon.Shared.Core.Attributes;
//using System.ComponentModel;
//using System.Diagnostics.CodeAnalysis;
//using System.Reflection;
//using System.Runtime.CompilerServices;
//using System.Text.Json;
//using System.Text.Json.Serialization;
//using System.Text.Json.Serialization.Metadata;

//namespace HubconTestClient
//{
//    public class ISecondTestContractProxy : BaseContractProxy, HubconTestDomain.ISecondTestContract
//    {
//        private JsonTypeInfo Create_HubconTestDomain_LoginCommand(JsonSerializerOptions options)
//        {
//            var info = JsonMetadataServices.CreateObjectInfo<global::HubconTestDomain.LoginCommand>(options, new JsonObjectInfoValues<global::HubconTestDomain.LoginCommand>
//            {
//                ConstructorParameterMetadataInitializer = () => new JsonParameterInfoValues[] {
//                new JsonParameterInfoValues {
//                    Name = "Username",
//                    ParameterType = typeof(string),
//                    Position = 0
//                },
//                new JsonParameterInfoValues {
//                    Name = "Password",
//                    ParameterType = typeof(string),
//                    Position = 1
//                },
//                new JsonParameterInfoValues {
//                    Name = "RememberMe",
//                    ParameterType = typeof(bool),
//                    Position = 2
//                },
//            },
//                ObjectWithParameterizedConstructorCreator = (args) => new global::HubconTestDomain.LoginCommand((string)args[0], (string)args[1], (bool)args[2]),
//                PropertyMetadataInitializer = (context) => new JsonPropertyInfo[] {
//                JsonMetadataServices.CreatePropertyInfo<string>(options, new JsonPropertyInfoValues<string> {
//                    PropertyName = "Username",
//                    Getter = (obj) => ((global::HubconTestDomain.LoginCommand)obj).Username,
//                    PropertyTypeInfo = options.GetTypeInfo(typeof(string)),
//                    public
//                }),
//                JsonMetadataServices.CreatePropertyInfo<string>(options, new JsonPropertyInfoValues<string> {
//                    PropertyName = "Password",
//                    Getter = (obj) => ((global::HubconTestDomain.LoginCommand)obj).Password,
//                    PropertyTypeInfo = options.GetTypeInfo(typeof(string)),
//                }),
//                JsonMetadataServices.CreatePropertyInfo<bool>(options, new JsonPropertyInfoValues<bool> {
//                    PropertyName = "RememberMe",
//                    Getter = (obj) => ((global::HubconTestDomain.LoginCommand)obj).RememberMe,
//                    PropertyTypeInfo = options.GetTypeInfo(typeof(bool)),
//                }),
//            }
//            });
//            return info;
//        }
//    }
//}
