<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<LangVersion>12.0</LangVersion>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>None</ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>
		<ServerGarbageCollection>false</ServerGarbageCollection>
		<UserSecretsId>13f2f7ca-4f92-42d8-84fa-908a9804f866</UserSecretsId>

		<!--		<DebugSymbols>true</DebugSymbols>-->
		<!--		<DebugType>portable</DebugType>-->
		<!--		<StripSymbols>false</StripSymbols>-->
		<!--		<StackTraceSupport>true</StackTraceSupport>-->
		
		<PublishAot>true</PublishAot>
		<IsAotCompatible>true</IsAotCompatible>
		<TrimMode>link</TrimMode>

		<PublishTrimmed>true</PublishTrimmed>
		<IsTrimmable>true</IsTrimmable>

		<OptimizationPreference>Speed</OptimizationPreference>
		<InterproceduralOptimization>true</InterproceduralOptimization>
		<OptimizationLevel>Experimental</OptimizationLevel>

		<EnableTrimAnalyzer>true</EnableTrimAnalyzer>
		<EnableAotAnalyzer>true</EnableAotAnalyzer>
		
		<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
		<MicrosoftExtensionsDependencyInjectionVerifyOpenGenericServiceTrimmability>true</MicrosoftExtensionsDependencyInjectionVerifyOpenGenericServiceTrimmability>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\Hubcon\Hubcon.csproj" />
		<ProjectReference Include="..\..\HubconTestDomain\HubconTestDomain.csproj" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\Analyzers\Hubcon.Analyzers.SourceGenerators\Hubcon.Analyzers.SourceGenerators.csproj"
		                  OutputItemType="Analyzer"
		                  ReferenceOutputAssembly="false" />
	</ItemGroup>

	<ItemGroup>
		<Content Update="runtimeconfig.template.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
	</ItemGroup>
</Project>