<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net5.0;netstandard2.1</TargetFrameworks>
		<Nullable>enable</Nullable>
		<LangVersion>9.0</LangVersion>

		<AssemblyName>$(AssemblyName)</AssemblyName>
		<RootNamespace>$(AssemblyName)</RootNamespace>
		<PackageId>$(AssemblyName)</PackageId>
		<PackageOutputPath>../nupkgs</PackageOutputPath>
		<IsPackable>true</IsPackable>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<Description>Shared module for Hubcon.</Description>
		<RepositoryUrl>https://github.com/Brick-Logic/Hubcon</RepositoryUrl>
		<PackageTags>rpc;dotnet;high-performance;native-aot;tcp;http;websockets</PackageTags>
		<Version>2.0.0-rc7</Version>
		<Authors>$(Authors)</Authors>
		<Company>$(Company)</Company>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<DebugType>embedded</DebugType>
		<Deterministic>True</Deterministic>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<DebugType>embedded</DebugType>
		<Deterministic>True</Deterministic>
	</PropertyGroup>
	
	<ItemGroup>
		<ProjectReference Include="..\Hubcon.Shared.Abstractions.Standard\Hubcon.Shared.Abstractions.Standard.csproj" />
		<ProjectReference Include="..\Hubcon.Shared.Abstractions\Hubcon.Shared.Abstractions.csproj" />
		<ProjectReference Include="..\Hubcon.Shared.Core\Hubcon.Shared.Core.csproj" />
	</ItemGroup>

	<ItemGroup Condition="( '$(SourceGeneratorDevelopment)' != 'true' )">
		<PackageReference Include="Hubcon.Analyzers" Version="$(AnalyzersRange)" />
		<PackageReference Include="Hubcon.Analyzers.CodeFixes" Version="$(AnalyzersCodeFixesRange)"/>
		<PackageReference Include="Hubcon.Analyzers.DiagnosticSuppressors" Version="$(AnalyzersDiagnosticSuppressorsRange)" />
	</ItemGroup>
	
	<ItemGroup>
	  <PackageReference Include="System.Text.Json" Version="[8.0.6, 11.0.0)" />
	</ItemGroup>
	
	<ItemGroup>
		<None Update="README.md">
			<PackagePath>./</PackagePath>
			<Pack>true</Pack>
		</None>
	</ItemGroup>
</Project>
