<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseHubconServer>true</UseHubconServer>
  </PropertyGroup>
	<ItemGroup>
        <PackageReference Include="Hubcon" Version="$(HubconUnifiedVersion)"/>
	</ItemGroup>
</Project>
