<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Hubcon" Version="2.0.0-rc1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HubconQuickStart.Shared\HubconQuickStart.Shared.csproj" />
  </ItemGroup>

</Project>
