<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<LangVersion>9.0</LangVersion>
		<Nullable>enable</Nullable>
		<IsHubconServer>false</IsHubconServer>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Hubcon" Version="2.0.0-rc1" />
	</ItemGroup>
</Project>
