<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<LangVersion>9.0</LangVersion>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Hubcon" Version="1.0.0-rc5" />
		<PackageReference Include="Hubcon.Analyzers.SourceGenerators" Version="1.0.168" />
	</ItemGroup>
</Project>
